[package]
name = "game"
version = "0.1.0"
authors = ["cheaterok <1cheaterok1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.1"
strum = "0.19.2"
strum_macros = "0.19"

creature = { path = "../creature" }
formats = { path = "../formats" }
