[package]
name = "game"
version = "0.1.0"
authors = ["cheaterok <1cheaterok1@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.34.1"
default-features = false
features = ["ttf"]

[dependencies]
strum = "0.19.2"
strum_macros = "0.19"

formats = { path = "../formats" }
