#[derive(Clone, Copy)]
#[allow(unused)]
pub enum Creature {
    // Castle
    Pikeman,
    Halberdier,
    Archer,
    Marksman,
    Griffin,
    RoyalGriffin,
    Swordsman,
    Crusader,
    Monk,
    Zealot,
    Cavalier,
    Champion,
    Angel,
    Archangel,
    // Rampart
    Centaur,
    CentaurCaptain,
    Dwarf,
    BattleDwarf,
    WoodElf,
    GrandElf,
    Pegasus,
    SilverPegasus,
    DendroidGuard,
    DendroidSoldier,
    Unicorn,
    WarUnicorn,
    GreenDragon,
    GoldDragon,
    // Tower,
    Gremlin,
    MasterGremlin,
    StoneGargoyle,
    ObsidianGargoyle,
    StoneGolem,
    IronGolem,
    Mage,
    ArchMage,
    Genie,
    MasterGenie,
    Naga,
    NagaQueen,
    Giant,
    Titan,
    // Stronghold,
    Goblin,
    Hobgoblin,
    WolfRider,
    WolfRaider,
    Orc,
    OrcChieftain,
    Ogre,
    OgreMagi,
    Roc,
    Thunderbird,
    Cyclops,
    CyclopsKing,
    Behemoth,
    AncientBehemoth,
    // Fortress,
    Gnoll,
    GnollMaradeur,
    Lizardman,
    LizardWarrior,
    SerpentFly,
    DragonFly,
    Basilisk,
    GreaterBasilisk,
    Gorgon,
    MightyGorgon,
    Wyvern,
    WyvernMonarch,
    Hydra,
    ChaosHydra,
    // Inferno
    Imp,
    Familiar,
    Gog,
    Magog,
    HellHound,
    Cerberus,
    Demon,
    HornedDemon,
    PitFiend,
    PitLord,
    Efreeti,
    EfreetSultan,
    Devil,
    ArchDevil,
    // Necropolis
    Skeleton,
    SkeletonWarrior,
    WalkingDead,
    Zombie,
    Wigth,
    Wraith,
    Vampire,
    VampireLord,
    Lich,
    PowerLich,
    BlackKnight,
    DreadKnight,
    BoneDragon,
    GhostDragon,
    // Dungeon
    Troglodyte,
    InfernalTroglodyte,
    Harpy,
    HarpyHag,
    Beholder,
    EvilEye,
    Medusa,
    MedusaQueen,
    Minotaur,
    MinotaurKing,
    Manticore,
    Scorpicore,
    RedDragon,
    BlackDragon,
    // Conflux
    Pixie,
    Sprite,
    AirElemental,
    StormElemental,
    WaterElemental,
    IceElemental,
    FireElemental,
    EnergyElemental,
    EarthElemental,
    MagmaElemental,
    PsychicElemental,
    MagicElemental,
    Firebird,
    Phoenix,
    // Neutral
    Peasant,
    Halfling,
    Boar,
    Rogue,
    Mummy,
    Nomad,
    Sharpshooter,
    Troll,
    GoldGolem,
    DiamondGolem,
    Enchanter,
    FaerieDragon,
    RustDragon,
    CrystalDragon,
    AzureDragon,
    // War Machines
    Ballista,
    FirstAidTent,
    Catapult,
    AmmoCart
}

impl Creature {
    pub const COUNT: usize = 145;

    pub const fn filename(self) -> &'static str {
        match self {
            // Castle
            Self::Pikeman => "CPKMAN.def",
            Self::Halberdier => "chalbd.def",
            Self::Archer => "CLCBOW.def",
            Self::Marksman => "CHCBOW.def",
            Self::Griffin => "CGRIFF.def",
            Self::RoyalGriffin => "Crgrif.def",
            Self::Swordsman => "Csword.def",
            Self::Crusader => "Ccrusd.def",
            Self::Monk => "Cmonkk.def",
            Self::Zealot => "Czealt.def",
            Self::Cavalier => "CCAVLR.def",
            Self::Champion => "CCHAMP.def",
            Self::Angel => "cangel.def",
            Self::Archangel => "CRANGL.def",
            // Rampart
            Self::Centaur => "CCENTR.def",
            Self::CentaurCaptain => "CECENT.def",
            Self::Dwarf => "CDWARF.def",
            Self::BattleDwarf => "CBDWAR.def",
            Self::WoodElf => "CELF.def",
            Self::GrandElf => "CGRELF.def",
            Self::Pegasus => "CPEGAS.def",
            Self::SilverPegasus => "CAPEGS.def",
            Self::DendroidGuard => "CTREE.def",
            Self::DendroidSoldier => "CBTREE.def",
            Self::Unicorn => "CUNICO.def",
            Self::WarUnicorn => "CWUNIC.def",
            Self::GreenDragon => "CGDRAG.def",
            Self::GoldDragon => "CDDRAG.def",
            // Tower
            Self::Gremlin => "CGREMA.def",
            Self::MasterGremlin => "CGREMM.def",
            Self::StoneGargoyle => "CGARGO.def",
            Self::ObsidianGargoyle => "COGARG.def",
            Self::StoneGolem => "CSGOLE.def",
            Self::IronGolem => "CIGOLE.def",
            Self::Mage => "CMAGE.def",
            Self::ArchMage => "CAMAGE.def",
            Self::Genie => "CGENIE.def",
            Self::MasterGenie => "CSULTA.def",
            Self::Naga => "CNAGA.def",
            Self::NagaQueen => "CNAGAG.def",
            Self::Giant => "CLTITA.def",
            Self::Titan => "CGTITA.def",
            // Stronghold
            Self::Goblin => "CGOBLI.def",
            Self::Hobgoblin => "CHGOBL.def",
            Self::WolfRider => "CBWLFR.def",
            Self::WolfRaider => "CUWLFR.def",
            Self::Orc => "CORC.def",
            Self::OrcChieftain => "CORCCH.def",
            Self::Ogre => "COGRE.def",
            Self::OgreMagi => "COGMAG.def",
            Self::Roc => "CROC.def",
            Self::Thunderbird => "CTBIRD.def",
            Self::Cyclops => "CCYCLR.def",
            Self::CyclopsKing => "CcyclLor.def",
            Self::Behemoth => "CYBEHE.def",
            Self::AncientBehemoth => "CABEHE.def",
            // Fortress
            Self::Gnoll => "CGNOLL.def",
            Self::GnollMaradeur => "CGNOLM.def",
            Self::Lizardman => "CPLIZA.def",
            Self::LizardWarrior => "CALIZA.def",
            Self::SerpentFly => "CDRFLY.def",
            Self::DragonFly => "CDRFIR.der",
            Self::Basilisk => "CBASIL.def",
            Self::GreaterBasilisk => "CGBASI.def",
            Self::Gorgon => "Ccgorg.def",
            Self::MightyGorgon => "Cbgog.def",
            Self::Wyvern => "CWYVER.def",
            Self::WyvernMonarch => "CWYVMN.def",
            Self::Hydra => "CHYDRA.def",
            Self::ChaosHydra => "cchydr.def",
            // Inferno
            Self::Imp => "CIMP.def",
            Self::Familiar => "CFAMIL.def",
            Self::Gog => "CGOG.def",
            Self::Magog => "CMAGOG.def",
            Self::HellHound => "CHHOUN.def",
            Self::Cerberus => "CCERBU.def",
            Self::Demon => "COHDEM.def",
            Self::HornedDemon => "CTHDEM.def",
            Self::PitFiend => "CPFIEN.def",
            Self::PitLord => "CPFOE.def",
            Self::Efreeti => "cefree.def",
            Self::EfreetSultan => "cefres.def",
            Self::Devil => "CDEVIL.def",
            Self::ArchDevil => "CADEVL.def",
            // Necropolis
            Self::Skeleton => "CSKELE.def",
            Self::SkeletonWarrior => "CWSKEL.def",
            Self::WalkingDead => "CZOMBI.def",
            Self::Zombie => "CZOMLO.def",
            Self::Wigth => "CWIGTH.def",
            Self::Wraith => "CWRAITH.def",
            Self::Vampire => "CVAMP.def",
            Self::VampireLord => "CNOSFE.def",
            Self::Lich => "CLICH.def",
            Self::PowerLich => "CPLICH.def",
            Self::BlackKnight => "CBKNIG.def",
            Self::DreadKnight => "CBLORD.def",
            Self::BoneDragon => "CNDRGN.def",
            Self::GhostDragon => "CHDRGN.def",
            // Dungeon
            Self::Troglodyte => "Ctrogl.def",
            Self::InfernalTroglodyte => "Citrog.def",
            Self::Harpy => "CHARPY.def",
            Self::HarpyHag => "CHARPH.def",
            Self::Beholder => "cbehol.def",
            Self::EvilEye => "Ceveye.def",
            Self::Medusa => "Cmedus.def",
            Self::MedusaQueen => "Cmeduq.def",
            Self::Minotaur => "CMINOT.def",
            Self::MinotaurKing => "Cminok.def",
            Self::Manticore => "CMCORE.def",
            Self::Scorpicore => "CCMCOR.def",
            Self::RedDragon => "CRDRGN.def",
            Self::BlackDragon => "CBDRGN.def",
            // Conflux
            Self::Pixie => "Cpixie.def",
            Self::Sprite => "CSprite.def",
            Self::AirElemental => "CAELEM.def",
            Self::StormElemental => "Cstorm.def",
            Self::WaterElemental => "CWELEM.def",
            Self::IceElemental => "Cicee.def",
            Self::FireElemental => "CFELEM.def",
            Self::EnergyElemental => "Cnrg.def",
            Self::EarthElemental => "CEELEM.def",
            Self::MagmaElemental => "Cstone.def",
            Self::PsychicElemental => "Cpsyel.def",
            Self::MagicElemental => "Cmagel.def",
            Self::Firebird => "Cfbird.DEF",
            Self::Phoenix => "Cphx.def",
            // Neutral
            Self::Peasant => "Cpeas.def",
            Self::Halfling => "CHalf.def",
            Self::Boar => "Cboar.def",
            Self::Rogue => "Crogue.def",
            Self::Mummy => "Cmummy.def",
            Self::Nomad => "Cnomad.def",
            Self::Sharpshooter => "Csharp.def",
            Self::Troll => "Ctroll.def",
            Self::GoldGolem => "CGGOLE.def",
            Self::DiamondGolem => "CDGOLE.def",
            Self::Enchanter => "Cench.def",
            Self::FaerieDragon => "Cfdrgn.def",
            Self::RustDragon => "CRsDgn.def",
            Self::CrystalDragon => "Ccdrgn.def",
            Self::AzureDragon => "CaDrgn.def",
            // War Machines
            Self::Ballista => "smbal.def",
            Self::FirstAidTent => "SMtent.def",
            Self::Catapult => "SMCata.def",
            Self::AmmoCart => "SMCart.def"
        }
    }
}
