use serde::Deserialize;
use strum_macros::EnumCount;

pub mod abilities;

use abilities::Ability;

#[derive(Clone, Copy, PartialEq, PartialOrd, Debug, Deserialize, EnumCount)]
pub enum Creature {
    // Castle
    Pikeman,
    Halberdier,
    Archer,
    Marksman,
    Griffin,
    RoyalGriffin,
    Swordsman,
    Crusader,
    Monk,
    Zealot,
    Cavalier,
    Champion,
    Angel,
    Archangel,
    // Rampart
    Centaur,
    CentaurCaptain,
    Dwarf,
    BattleDwarf,
    WoodElf,
    GrandElf,
    Pegasus,
    SilverPegasus,
    DendroidGuard,
    DendroidSoldier,
    Unicorn,
    WarUnicorn,
    GreenDragon,
    GoldDragon,
    // Tower
    Gremlin,
    MasterGremlin,
    StoneGargoyle,
    ObsidianGargoyle,
    StoneGolem,
    IronGolem,
    Mage,
    ArchMage,
    Genie,
    MasterGenie,
    Naga,
    NagaQueen,
    Giant,
    Titan,
    // Inferno
    Imp,
    Familiar,
    Gog,
    Magog,
    HellHound,
    Cerberus,
    Demon,
    HornedDemon,
    PitFiend,
    PitLord,
    Efreeti,
    EfreetSultan,
    Devil,
    ArchDevil,
    // Necropolis
    Skeleton,
    SkeletonWarrior,
    WalkingDead,
    Zombie,
    Wight,
    Wraith,
    Vampire,
    VampireLord,
    Lich,
    PowerLich,
    BlackKnight,
    DreadKnight,
    BoneDragon,
    GhostDragon,
    // Dungeon
    Troglodyte,
    InfernalTroglodyte,
    Harpy,
    HarpyHag,
    Beholder,
    EvilEye,
    Medusa,
    MedusaQueen,
    Minotaur,
    MinotaurKing,
    Manticore,
    Scorpicore,
    RedDragon,
    BlackDragon,
    // Stronghold
    Goblin,
    Hobgoblin,
    WolfRider,
    WolfRaider,
    Orc,
    OrcChieftain,
    Ogre,
    OgreMagi,
    Roc,
    Thunderbird,
    Cyclops,
    CyclopsKing,
    Behemoth,
    AncientBehemoth,
    // Fortress
    Gnoll,
    GnollMarauder,
    Lizardman,
    LizardWarrior,
    SerpentFly,
    DragonFly,
    Basilisk,
    GreaterBasilisk,
    Gorgon,
    MightyGorgon,
    Wyvern,
    WyvernMonarch,
    Hydra,
    ChaosHydra,
    // Conflux
    Pixie,
    Sprite,
    AirElemental,
    StormElemental,
    WaterElemental,
    IceElemental,
    FireElemental,
    EnergyElemental,
    EarthElemental,
    MagmaElemental,
    PsychicElemental,
    MagicElemental,
    Firebird,
    Phoenix,
    // Neutral
    Peasant,
    Halfling,
    Boar,
    Rogue,
    Mummy,
    Nomad,
    Sharpshooter,
    Troll,
    GoldGolem,
    DiamondGolem,
    Enchanter,
    FaerieDragon,
    RustDragon,
    CrystalDragon,
    AzureDragon,
    // War Machines
    Ballista,
    FirstAidTent,
    Catapult,
    AmmoCart,
}

pub struct CreatureStats {
    pub level: u8,
    pub attack: u8,
    pub defence: u8,
    pub damage: (i32, i32),
    pub health: u16,
    pub speed: u8,
    pub ammo_capacity: u8,
}

type C = Creature;
type CS = CreatureStats;

impl Creature {
    pub const fn base_stats(&self) -> CreatureStats {
        match self {
            // Castle
            Self::Pikeman => CS {
                level: 1,
                attack: 4,
                defence: 5,
                damage: (1, 3),
                health: 10,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Halberdier => CS {
                level: 1,
                attack: 6,
                defence: 5,
                damage: (2, 3),
                health: 10,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Archer => CS {
                level: 2,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::Marksman => CS {
                level: 2,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::Griffin => CS {
                level: 3,
                attack: 8,
                defence: 8,
                damage: (3, 6),
                health: 25,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::RoyalGriffin => CS {
                level: 3,
                attack: 9,
                defence: 9,
                damage: (3, 6),
                health: 25,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Swordsman => CS {
                level: 4,
                attack: 10,
                defence: 12,
                damage: (6, 9),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Crusader => CS {
                level: 4,
                attack: 12,
                defence: 12,
                damage: (7, 10),
                health: 35,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Monk => CS {
                level: 5,
                attack: 12,
                defence: 7,
                damage: (10, 12),
                health: 30,
                speed: 5,
                ammo_capacity: 12,
            },
            Self::Zealot => CS {
                level: 5,
                attack: 12,
                defence: 10,
                damage: (10, 12),
                health: 30,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Cavalier => CS {
                level: 6,
                attack: 15,
                defence: 15,
                damage: (15, 25),
                health: 100,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Champion => CS {
                level: 6,
                attack: 16,
                defence: 16,
                damage: (20, 25),
                health: 100,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Angel => CS {
                level: 7,
                attack: 20,
                defence: 20,
                damage: (50, 50),
                health: 200,
                speed: 12,
                ammo_capacity: 0,
            },
            Self::Archangel => CS {
                level: 7,
                attack: 30,
                defence: 30,
                damage: (50, 50),
                health: 250,
                speed: 18,
                ammo_capacity: 0,
            },
            // Rampart
            Self::Centaur => CS {
                level: 1,
                attack: 5,
                defence: 3,
                damage: (2, 3),
                health: 8,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::CentaurCaptain => CS {
                level: 1,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Dwarf => CS {
                level: 2,
                attack: 6,
                defence: 7,
                damage: (2, 4),
                health: 20,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::BattleDwarf => CS {
                level: 2,
                attack: 7,
                defence: 7,
                damage: (2, 4),
                health: 20,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::WoodElf => CS {
                level: 3,
                attack: 9,
                defence: 5,
                damage: (3, 5),
                health: 15,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::GrandElf => CS {
                level: 3,
                attack: 9,
                defence: 5,
                damage: (3, 5),
                health: 15,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Pegasus => CS {
                level: 4,
                attack: 9,
                defence: 8,
                damage: (5, 9),
                health: 30,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::SilverPegasus => CS {
                level: 4,
                attack: 9,
                defence: 10,
                damage: (5, 9),
                health: 30,
                speed: 12,
                ammo_capacity: 0,
            },
            Self::DendroidGuard => CS {
                level: 5,
                attack: 9,
                defence: 12,
                damage: (10, 14),
                health: 55,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::DendroidSoldier => CS {
                level: 5,
                attack: 9,
                defence: 12,
                damage: (10, 14),
                health: 65,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Unicorn => CS {
                level: 6,
                attack: 15,
                defence: 14,
                damage: (18, 22),
                health: 90,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WarUnicorn => CS {
                level: 6,
                attack: 15,
                defence: 14,
                damage: (18, 22),
                health: 110,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::GreenDragon => CS {
                level: 7,
                attack: 18,
                defence: 18,
                damage: (40, 50),
                health: 180,
                speed: 10,
                ammo_capacity: 0,
            },
            Self::GoldDragon => CS {
                level: 7,
                attack: 27,
                defence: 27,
                damage: (40, 50),
                health: 250,
                speed: 16,
                ammo_capacity: 0,
            },
            // Tower
            Self::Gremlin => CS {
                level: 1,
                attack: 3,
                defence: 3,
                damage: (1, 2),
                health: 4,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::MasterGremlin => CS {
                level: 1,
                attack: 4,
                defence: 4,
                damage: (1, 2),
                health: 4,
                speed: 5,
                ammo_capacity: 8,
            },
            Self::StoneGargoyle => CS {
                level: 2,
                attack: 6,
                defence: 6,
                damage: (2, 3),
                health: 16,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::ObsidianGargoyle => CS {
                level: 2,
                attack: 7,
                defence: 7,
                damage: (2, 3),
                health: 16,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::StoneGolem => CS {
                level: 3,
                attack: 7,
                defence: 10,
                damage: (4, 5),
                health: 30,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::IronGolem => CS {
                level: 3,
                attack: 9,
                defence: 10,
                damage: (4, 5),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Mage => CS {
                level: 4,
                attack: 11,
                defence: 8,
                damage: (7, 9),
                health: 25,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::ArchMage => CS {
                level: 4,
                attack: 12,
                defence: 9,
                damage: (7, 9),
                health: 30,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Genie => CS {
                level: 5,
                attack: 12,
                defence: 12,
                damage: (13, 16),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::MasterGenie => CS {
                level: 5,
                attack: 12,
                defence: 12,
                damage: (13, 16),
                health: 40,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Naga => CS {
                level: 6,
                attack: 16,
                defence: 13,
                damage: (20, 20),
                health: 110,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::NagaQueen => CS {
                level: 6,
                attack: 16,
                defence: 13,
                damage: (30, 30),
                health: 110,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Giant => CS {
                level: 7,
                attack: 19,
                defence: 16,
                damage: (40, 60),
                health: 150,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Titan => CS {
                level: 7,
                attack: 24,
                defence: 24,
                damage: (40, 60),
                health: 300,
                speed: 11,
                ammo_capacity: 24,
            },
            // Inferno
            Self::Imp => CS {
                level: 1,
                attack: 2,
                defence: 3,
                damage: (1, 2),
                health: 4,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Familiar => CS {
                level: 1,
                attack: 4,
                defence: 4,
                damage: (1, 2),
                health: 4,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Gog => CS {
                level: 2,
                attack: 6,
                defence: 4,
                damage: (2, 4),
                health: 13,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::Magog => CS {
                level: 2,
                attack: 7,
                defence: 4,
                damage: (2, 4),
                health: 13,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::HellHound => CS {
                level: 3,
                attack: 10,
                defence: 6,
                damage: (2, 7),
                health: 25,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Cerberus => CS {
                level: 3,
                attack: 10,
                defence: 8,
                damage: (2, 7),
                health: 25,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Demon => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (7, 9),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::HornedDemon => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (7, 9),
                health: 40,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PitFiend => CS {
                level: 5,
                attack: 13,
                defence: 13,
                damage: (13, 17),
                health: 45,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PitLord => CS {
                level: 5,
                attack: 13,
                defence: 13,
                damage: (13, 17),
                health: 45,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Efreeti => CS {
                level: 6,
                attack: 16,
                defence: 12,
                damage: (16, 24),
                health: 90,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::EfreetSultan => CS {
                level: 6,
                attack: 16,
                defence: 14,
                damage: (16, 24),
                health: 90,
                speed: 13,
                ammo_capacity: 0,
            },
            Self::Devil => CS {
                level: 7,
                attack: 19,
                defence: 21,
                damage: (30, 40),
                health: 160,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::ArchDevil => CS {
                level: 7,
                attack: 26,
                defence: 28,
                damage: (30, 40),
                health: 200,
                speed: 17,
                ammo_capacity: 0,
            },
            // Necropolis
            Self::Skeleton => CS {
                level: 1,
                attack: 5,
                defence: 4,
                damage: (1, 3),
                health: 6,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::SkeletonWarrior => CS {
                level: 1,
                attack: 6,
                defence: 6,
                damage: (1, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::WalkingDead => CS {
                level: 2,
                attack: 5,
                defence: 5,
                damage: (2, 3),
                health: 15,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::Zombie => CS {
                level: 2,
                attack: 5,
                defence: 5,
                damage: (2, 3),
                health: 20,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Wight => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 18,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Wraith => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 18,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Vampire => CS {
                level: 4,
                attack: 10,
                defence: 9,
                damage: (5, 8),
                health: 30,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::VampireLord => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (5, 8),
                health: 40,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Lich => CS {
                level: 5,
                attack: 13,
                defence: 10,
                damage: (11, 13),
                health: 30,
                speed: 6,
                ammo_capacity: 12,
            },
            Self::PowerLich => CS {
                level: 5,
                attack: 13,
                defence: 10,
                damage: (11, 15),
                health: 40,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::BlackKnight => CS {
                level: 6,
                attack: 16,
                defence: 16,
                damage: (15, 30),
                health: 120,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::DreadKnight => CS {
                level: 6,
                attack: 18,
                defence: 18,
                damage: (15, 30),
                health: 120,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::BoneDragon => CS {
                level: 7,
                attack: 17,
                defence: 15,
                damage: (25, 50),
                health: 150,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::GhostDragon => CS {
                level: 7,
                attack: 19,
                defence: 17,
                damage: (25, 50),
                health: 200,
                speed: 14,
                ammo_capacity: 0,
            },
            // Dungeon
            Self::Troglodyte => CS {
                level: 1,
                attack: 4,
                defence: 3,
                damage: (1, 3),
                health: 5,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::InfernalTroglodyte => CS {
                level: 1,
                attack: 5,
                defence: 4,
                damage: (1, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Harpy => CS {
                level: 2,
                attack: 6,
                defence: 5,
                damage: (1, 4),
                health: 14,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::HarpyHag => CS {
                level: 2,
                attack: 6,
                defence: 6,
                damage: (1, 4),
                health: 14,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Beholder => CS {
                level: 3,
                attack: 9,
                defence: 7,
                damage: (3, 5),
                health: 22,
                speed: 5,
                ammo_capacity: 12,
            },
            Self::EvilEye => CS {
                level: 3,
                attack: 10,
                defence: 8,
                damage: (3, 5),
                health: 22,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Medusa => CS {
                level: 4,
                attack: 9,
                defence: 9,
                damage: (6, 8),
                health: 25,
                speed: 5,
                ammo_capacity: 4,
            },
            Self::MedusaQueen => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (6, 8),
                health: 30,
                speed: 6,
                ammo_capacity: 8,
            },
            Self::Minotaur => CS {
                level: 5,
                attack: 14,
                defence: 12,
                damage: (12, 20),
                health: 50,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::MinotaurKing => CS {
                level: 5,
                attack: 15,
                defence: 15,
                damage: (12, 20),
                health: 50,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Manticore => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (14, 20),
                health: 80,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Scorpicore => CS {
                level: 6,
                attack: 16,
                defence: 14,
                damage: (14, 20),
                health: 80,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::RedDragon => CS {
                level: 7,
                attack: 19,
                defence: 19,
                damage: (40, 50),
                health: 180,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::BlackDragon => CS {
                level: 7,
                attack: 25,
                defence: 25,
                damage: (40, 50),
                health: 300,
                speed: 15,
                ammo_capacity: 0,
            },
            // Stronghold
            Self::Goblin => CS {
                level: 1,
                attack: 4,
                defence: 2,
                damage: (1, 2),
                health: 5,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Hobgoblin => CS {
                level: 1,
                attack: 5,
                defence: 3,
                damage: (1, 2),
                health: 5,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WolfRider => CS {
                level: 2,
                attack: 7,
                defence: 5,
                damage: (2, 4),
                health: 10,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::WolfRaider => CS {
                level: 2,
                attack: 8,
                defence: 5,
                damage: (3, 4),
                health: 10,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Orc => CS {
                level: 3,
                attack: 8,
                defence: 4,
                damage: (2, 5),
                health: 15,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::OrcChieftain => CS {
                level: 3,
                attack: 8,
                defence: 4,
                damage: (2, 5),
                health: 20,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::Ogre => CS {
                level: 4,
                attack: 13,
                defence: 7,
                damage: (6, 12),
                health: 40,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::OgreMagi => CS {
                level: 4,
                attack: 13,
                defence: 7,
                damage: (6, 12),
                health: 60,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Roc => CS {
                level: 5,
                attack: 13,
                defence: 11,
                damage: (11, 15),
                health: 60,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Thunderbird => CS {
                level: 5,
                attack: 13,
                defence: 11,
                damage: (11, 15),
                health: 60,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Cyclops => CS {
                level: 6,
                attack: 15,
                defence: 12,
                damage: (16, 20),
                health: 70,
                speed: 6,
                ammo_capacity: 16,
            },
            Self::CyclopsKing => CS {
                level: 6,
                attack: 17,
                defence: 13,
                damage: (16, 20),
                health: 70,
                speed: 8,
                ammo_capacity: 24,
            },
            Self::Behemoth => CS {
                level: 7,
                attack: 17,
                defence: 17,
                damage: (30, 50),
                health: 160,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::AncientBehemoth => CS {
                level: 7,
                attack: 19,
                defence: 19,
                damage: (30, 50),
                health: 300,
                speed: 9,
                ammo_capacity: 0,
            },
            // Fortress
            Self::Gnoll => CS {
                level: 1,
                attack: 3,
                defence: 5,
                damage: (2, 3),
                health: 6,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::GnollMarauder => CS {
                level: 1,
                attack: 4,
                defence: 6,
                damage: (2, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Lizardman => CS {
                level: 2,
                attack: 5,
                defence: 6,
                damage: (2, 3),
                health: 14,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::LizardWarrior => CS {
                level: 2,
                attack: 6,
                defence: 8,
                damage: (2, 5),
                health: 15,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::SerpentFly => CS {
                level: 3,
                attack: 7,
                defence: 9,
                damage: (2, 5),
                health: 20,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::DragonFly => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (2, 5),
                health: 20,
                speed: 13,
                ammo_capacity: 0,
            },
            Self::Basilisk => CS {
                level: 4,
                attack: 11,
                defence: 11,
                damage: (6, 10),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::GreaterBasilisk => CS {
                level: 4,
                attack: 12,
                defence: 12,
                damage: (6, 10),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Gorgon => CS {
                level: 5,
                attack: 10,
                defence: 14,
                damage: (12, 16),
                health: 70,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::MightyGorgon => CS {
                level: 5,
                attack: 11,
                defence: 16,
                damage: (12, 16),
                health: 70,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Wyvern => CS {
                level: 6,
                attack: 14,
                defence: 14,
                damage: (14, 18),
                health: 70,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WyvernMonarch => CS {
                level: 6,
                attack: 14,
                defence: 14,
                damage: (18, 22),
                health: 70,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Hydra => CS {
                level: 7,
                attack: 16,
                defence: 18,
                damage: (25, 45),
                health: 175,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::ChaosHydra => CS {
                level: 7,
                attack: 18,
                defence: 20,
                damage: (25, 45),
                health: 250,
                speed: 7,
                ammo_capacity: 0,
            },
            // Conflux
            Self::Pixie => CS {
                level: 1,
                attack: 2,
                defence: 2,
                damage: (1, 2),
                health: 3,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Sprite => CS {
                level: 1,
                attack: 2,
                defence: 2,
                damage: (1, 3),
                health: 3,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::AirElemental => CS {
                level: 2,
                attack: 9,
                defence: 9,
                damage: (2, 8),
                health: 25,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::StormElemental => CS {
                level: 2,
                attack: 9,
                defence: 9,
                damage: (2, 8),
                health: 25,
                speed: 8,
                ammo_capacity: 24,
            },
            Self::WaterElemental => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (3, 7),
                health: 30,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::IceElemental => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (3, 7),
                health: 30,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::FireElemental => CS {
                level: 4,
                attack: 10,
                defence: 8,
                damage: (4, 6),
                health: 35,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::EnergyElemental => CS {
                level: 4,
                attack: 12,
                defence: 8,
                damage: (4, 6),
                health: 35,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::EarthElemental => CS {
                level: 5,
                attack: 10,
                defence: 10,
                damage: (4, 8),
                health: 40,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::MagmaElemental => CS {
                level: 5,
                attack: 11,
                defence: 11,
                damage: (6, 10),
                health: 40,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PsychicElemental => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (10, 20),
                health: 75,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::MagicElemental => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (15, 25),
                health: 80,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Firebird => CS {
                level: 7,
                attack: 18,
                defence: 18,
                damage: (30, 40),
                health: 150,
                speed: 15,
                ammo_capacity: 0,
            },
            Self::Phoenix => CS {
                level: 7,
                attack: 21,
                defence: 18,
                damage: (30, 40),
                health: 200,
                speed: 21,
                ammo_capacity: 0,
            },
            // Neutral
            Self::Peasant => CS {
                level: 1,
                attack: 1,
                defence: 1,
                damage: (1, 1),
                health: 1,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::Halfling => CS {
                level: 1,
                attack: 4,
                defence: 2,
                damage: (1, 3),
                health: 4,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::Boar => CS {
                level: 2,
                attack: 6,
                defence: 5,
                damage: (2, 3),
                health: 15,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Rogue => CS {
                level: 2,
                attack: 8,
                defence: 3,
                damage: (2, 4),
                health: 10,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Mummy => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 30,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Nomad => CS {
                level: 3,
                attack: 9,
                defence: 8,
                damage: (2, 6),
                health: 30,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Sharpshooter => CS {
                level: 4,
                attack: 12,
                defence: 10,
                damage: (8, 10),
                health: 15,
                speed: 9,
                ammo_capacity: 32,
            },
            Self::Troll => CS {
                level: 5,
                attack: 14,
                defence: 7,
                damage: (10, 15),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::GoldGolem => CS {
                level: 5,
                attack: 11,
                defence: 12,
                damage: (8, 10),
                health: 50,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::DiamondGolem => CS {
                level: 6,
                attack: 13,
                defence: 12,
                damage: (10, 14),
                health: 60,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Enchanter => CS {
                level: 6,
                attack: 17,
                defence: 12,
                damage: (14, 14),
                health: 30,
                speed: 9,
                ammo_capacity: 32,
            },
            Self::FaerieDragon => CS {
                level: 7,
                attack: 20,
                defence: 20,
                damage: (20, 30),
                health: 500,
                speed: 15,
                ammo_capacity: 0,
            },
            Self::RustDragon => CS {
                level: 7,
                attack: 30,
                defence: 30,
                damage: (50, 50),
                health: 750,
                speed: 17,
                ammo_capacity: 0,
            },
            Self::CrystalDragon => CS {
                level: 7,
                attack: 40,
                defence: 40,
                damage: (60, 75),
                health: 800,
                speed: 16,
                ammo_capacity: 0,
            },
            Self::AzureDragon => CS {
                level: 7,
                attack: 50,
                defence: 50,
                damage: (70, 80),
                health: 1000,
                speed: 19,
                ammo_capacity: 0,
            },
            // War Machines
            Self::Ballista => CS {
                level: 1,
                attack: 10,
                defence: 10,
                damage: (2, 3),
                health: 250,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::FirstAidTent => CS {
                level: 1,
                attack: 0,
                defence: 0,
                damage: (0, 0),
                health: 75,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::Catapult => CS {
                level: 1,
                attack: 10,
                defence: 10,
                damage: (0, 0),
                health: 1000,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::AmmoCart => CS {
                level: 1,
                attack: 0,
                defence: 5,
                damage: (0, 0),
                health: 100,
                speed: 0,
                ammo_capacity: 0,
            },
        }
    }

    pub fn has_ability(self, ability: Ability) -> bool {
        self.abilities()
            .into_iter()
            .any(|a| std::mem::discriminant(&ability) == std::mem::discriminant(&a))
    }

    pub fn abilities(self) -> Vec<Ability> {
        let angels = [Creature::Angel, Creature::Archangel];
        let devils = [Creature::Devil, Creature::ArchDevil];
        let genies = [Creature::Genie, Creature::MasterGenie];
        let efreets = [Creature::Efreeti, Creature::EfreetSultan];

        match self {
            Self::Marksman => vec![Ability::DoubleShot],
            Self::Griffin => vec![Ability::ExtraRetaliations {
                count: abilities::RetaliationCount::Finite(1),
            }],
            Self::RoyalGriffin => vec![Ability::ExtraRetaliations {
                count: abilities::RetaliationCount::Infinite,
            }],
            Self::Crusader => vec![Ability::DoubleStrike],
            Self::Angel => vec![Ability::Hatred {
                to: Box::new(devils),
            }],
            Self::Archangel => vec![Ability::Hatred {
                to: Box::new(devils),
            }],

            Self::Genie => vec![Ability::Hatred {
                to: Box::new(efreets),
            }],
            Self::MasterGenie => vec![Ability::Hatred {
                to: Box::new(efreets),
            }],
            Self::Naga => vec![Ability::NoRetaliation],
            Self::NagaQueen => vec![Ability::NoRetaliation],
            Self::Titan => vec![Ability::Hatred {
                to: Box::new([Creature::BlackDragon]),
            }],

            Self::Harpy => vec![Ability::NoRetaliation],
            Self::HarpyHag => vec![Ability::NoRetaliation, Ability::ReturnAfterStrike],

            Self::Cerberus => vec![Ability::NoRetaliation],
            Self::Efreeti => vec![Ability::Hatred {
                to: Box::new(genies),
            }],
            Self::EfreetSultan => vec![Ability::Hatred {
                to: Box::new(genies),
            }],
            Self::Devil => vec![
                Ability::NoRetaliation,
                Ability::Hatred {
                    to: Box::new(angels),
                },
            ],
            Self::ArchDevil => vec![
                Ability::NoRetaliation,
                Ability::Hatred {
                    to: Box::new(angels),
                },
            ],

            Self::Vampire => vec![Ability::NoRetaliation],
            Self::VampireLord => vec![Ability::NoRetaliation],

            Self::WolfRaider => vec![Ability::DoubleStrike],
            Self::Behemoth => vec![Ability::IgnoreDefence { percent: 0.4 }],
            Self::AncientBehemoth => vec![Ability::IgnoreDefence { percent: 0.8 }],

            Self::Hydra => vec![Ability::NoRetaliation],
            Self::ChaosHydra => vec![Ability::NoRetaliation],

            Self::Sprite => vec![Ability::NoRetaliation],
            Self::PsychicElemental => vec![Ability::NoRetaliation],
            Self::MagicElemental => vec![Ability::NoRetaliation],

            _ => vec![],
        }
    }

    pub fn is_wide(&self) -> bool {
        const WIDE_CREATURES: [Creature; 53] = [
            // Castle
            C::Griffin,
            C::RoyalGriffin,
            C::Cavalier,
            C::Champion,
            C::Archangel,
            // Rampart
            C::Centaur,
            C::CentaurCaptain,
            C::Pegasus,
            C::SilverPegasus,
            C::Unicorn,
            C::WarUnicorn,
            C::GreenDragon,
            C::GoldDragon,
            // Tower
            C::Naga,
            C::NagaQueen,
            // Inferno
            C::HellHound,
            C::Cerberus,
            // Necropolis
            C::BlackKnight,
            C::DreadKnight,
            C::BoneDragon,
            C::GhostDragon,
            // Dungeon
            C::Medusa,
            C::MedusaQueen,
            C::Manticore,
            C::Scorpicore,
            C::RedDragon,
            C::BlackDragon,
            // Stronghold
            C::WolfRider,
            C::WolfRaider,
            C::Roc,
            C::Thunderbird,
            C::Behemoth,
            C::AncientBehemoth,
            // Fortress
            C::Basilisk,
            C::GreaterBasilisk,
            C::Gorgon,
            C::MightyGorgon,
            C::Wyvern,
            C::WyvernMonarch,
            C::Hydra,
            C::ChaosHydra,
            // Conflux
            C::WaterElemental,
            C::IceElemental,
            C::Firebird,
            C::Phoenix,
            // Neutral
            C::Boar,
            C::Nomad,
            C::FaerieDragon,
            C::RustDragon,
            C::CrystalDragon,
            C::AzureDragon,
            // War Machines
            C::Ballista,
            C::Catapult,
        ];
        WIDE_CREATURES.contains(self)
    }

    pub fn is_flying(&self) -> bool {
        const FLYING_CREATURES: [Creature; 42] = [
            // Castle
            C::Griffin,
            C::RoyalGriffin,
            C::Angel,
            C::Archangel,
            // Rampart
            C::Pegasus,
            C::SilverPegasus,
            C::GreenDragon,
            C::GoldDragon,
            // Tower
            C::StoneGargoyle,
            C::ObsidianGargoyle,
            C::Genie,
            C::MasterGenie,
            // Inferno
            C::Efreeti,
            C::EfreetSultan,
            C::Devil,
            C::ArchDevil,
            // Necropolis
            C::Wight,
            C::Wraith,
            C::Vampire,
            C::VampireLord,
            C::BoneDragon,
            C::GhostDragon,
            // Dungeon
            C::Harpy,
            C::HarpyHag,
            C::Manticore,
            C::Scorpicore,
            C::RedDragon,
            C::BlackDragon,
            // Stronghold
            C::Roc,
            C::Thunderbird,
            // Fortress
            C::SerpentFly,
            C::DragonFly,
            C::Wyvern,
            C::WyvernMonarch,
            // Conflux
            C::Pixie,
            C::Sprite,
            C::EnergyElemental,
            C::Firebird,
            C::Phoenix,
            // Neutral
            C::FaerieDragon,
            C::RustDragon,
            C::AzureDragon,
        ];
        FLYING_CREATURES.contains(self)
    }

    pub fn is_teleporting(&self) -> bool {
        const TELEPORTING_CREATURES: [Creature; 2] = [Creature::Devil, Creature::ArchDevil];
        TELEPORTING_CREATURES.contains(self)
    }

    pub const fn spritesheet_filename(self) -> &'static str {
        match self {
            // Castle
            Self::Pikeman => "CPKMAN.def",
            Self::Halberdier => "chalbd.def",
            Self::Archer => "CLCBOW.def",
            Self::Marksman => "CHCBOW.def",
            Self::Griffin => "CGRIFF.def",
            Self::RoyalGriffin => "Crgrif.def",
            Self::Swordsman => "Csword.def",
            Self::Crusader => "Ccrusd.def",
            Self::Monk => "Cmonkk.def",
            Self::Zealot => "Czealt.def",
            Self::Cavalier => "CCAVLR.def",
            Self::Champion => "CCHAMP.def",
            Self::Angel => "cangel.def",
            Self::Archangel => "CRANGL.def",
            // Rampart
            Self::Centaur => "CCENTR.def",
            Self::CentaurCaptain => "CECENT.def",
            Self::Dwarf => "CDWARF.def",
            Self::BattleDwarf => "CBDWAR.def",
            Self::WoodElf => "CELF.def",
            Self::GrandElf => "CGRELF.def",
            Self::Pegasus => "CPEGAS.def",
            Self::SilverPegasus => "CAPEGS.def",
            Self::DendroidGuard => "CTREE.def",
            Self::DendroidSoldier => "CBTREE.def",
            Self::Unicorn => "CUNICO.def",
            Self::WarUnicorn => "CWUNIC.def",
            Self::GreenDragon => "CGDRAG.def",
            Self::GoldDragon => "CDDRAG.def",
            // Tower
            Self::Gremlin => "CGREMA.def",
            Self::MasterGremlin => "CGREMM.def",
            Self::StoneGargoyle => "CGARGO.def",
            Self::ObsidianGargoyle => "COGARG.def",
            Self::StoneGolem => "CSGOLE.def",
            Self::IronGolem => "CIGOLE.def",
            Self::Mage => "CMAGE.def",
            Self::ArchMage => "CAMAGE.def",
            Self::Genie => "CGENIE.def",
            Self::MasterGenie => "CSULTA.def",
            Self::Naga => "CNAGA.def",
            Self::NagaQueen => "CNAGAG.def",
            Self::Giant => "CLTITA.def",
            Self::Titan => "CGTITA.def",
            // Stronghold
            Self::Goblin => "CGOBLI.def",
            Self::Hobgoblin => "CHGOBL.def",
            Self::WolfRider => "CBWLFR.def",
            Self::WolfRaider => "CUWLFR.def",
            Self::Orc => "CORC.def",
            Self::OrcChieftain => "CORCCH.def",
            Self::Ogre => "COGRE.def",
            Self::OgreMagi => "COGMAG.def",
            Self::Roc => "CROC.def",
            Self::Thunderbird => "CTBIRD.def",
            Self::Cyclops => "CCYCLR.def",
            Self::CyclopsKing => "CcyclLor.def",
            Self::Behemoth => "CYBEHE.def",
            Self::AncientBehemoth => "CABEHE.def",
            // Fortress
            Self::Gnoll => "CGNOLL.def",
            Self::GnollMarauder => "CGNOLM.def",
            Self::Lizardman => "CPLIZA.def",
            Self::LizardWarrior => "CALIZA.def",
            Self::SerpentFly => "CDRFLY.def",
            Self::DragonFly => "CDRFIR.def",
            Self::Basilisk => "CBASIL.def",
            Self::GreaterBasilisk => "CGBASI.def",
            Self::Gorgon => "Ccgorg.def",
            Self::MightyGorgon => "Cbgog.def",
            Self::Wyvern => "CWYVER.def",
            Self::WyvernMonarch => "CWYVMN.def",
            Self::Hydra => "CHYDRA.def",
            Self::ChaosHydra => "cchydr.def",
            // Inferno
            Self::Imp => "CIMP.def",
            Self::Familiar => "CFAMIL.def",
            Self::Gog => "CGOG.def",
            Self::Magog => "CMAGOG.def",
            Self::HellHound => "CHHOUN.def",
            Self::Cerberus => "CCERBU.def",
            Self::Demon => "COHDEM.def",
            Self::HornedDemon => "CTHDEM.def",
            Self::PitFiend => "CPFIEN.def",
            Self::PitLord => "CPFOE.def",
            Self::Efreeti => "cefree.def",
            Self::EfreetSultan => "cefres.def",
            Self::Devil => "CDEVIL.def",
            Self::ArchDevil => "CADEVL.def",
            // Necropolis
            Self::Skeleton => "CSKELE.def",
            Self::SkeletonWarrior => "CWSKEL.def",
            Self::WalkingDead => "CZOMBI.def",
            Self::Zombie => "CZOMLO.def",
            Self::Wight => "CWIGHT.def",
            Self::Wraith => "CWRAIT.def",
            Self::Vampire => "CVAMP.def",
            Self::VampireLord => "CNOSFE.def",
            Self::Lich => "CLICH.def",
            Self::PowerLich => "CPLICH.def",
            Self::BlackKnight => "CBKNIG.def",
            Self::DreadKnight => "CBLORD.def",
            Self::BoneDragon => "CNDRGN.def",
            Self::GhostDragon => "CHDRGN.def",
            // Dungeon
            Self::Troglodyte => "Ctrogl.def",
            Self::InfernalTroglodyte => "Citrog.def",
            Self::Harpy => "CHARPY.def",
            Self::HarpyHag => "CHARPH.def",
            Self::Beholder => "cbehol.def",
            Self::EvilEye => "Ceveye.def",
            Self::Medusa => "Cmedus.def",
            Self::MedusaQueen => "Cmeduq.def",
            Self::Minotaur => "CMINOT.def",
            Self::MinotaurKing => "Cminok.def",
            Self::Manticore => "CMCORE.def",
            Self::Scorpicore => "CCMCOR.def",
            Self::RedDragon => "CRDRGN.def",
            Self::BlackDragon => "CBDRGN.def",
            // Conflux
            Self::Pixie => "Cpixie.def",
            Self::Sprite => "CSprite.def",
            Self::AirElemental => "CAELEM.def",
            Self::StormElemental => "Cstorm.def",
            Self::WaterElemental => "CWELEM.def",
            Self::IceElemental => "Cicee.def",
            Self::FireElemental => "CFELEM.def",
            Self::EnergyElemental => "Cnrg.def",
            Self::EarthElemental => "CEELEM.def",
            Self::MagmaElemental => "Cstone.def",
            Self::PsychicElemental => "Cpsyel.def",
            Self::MagicElemental => "Cmagel.def",
            Self::Firebird => "Cfbird.DEF",
            Self::Phoenix => "Cphx.def",
            // Neutral
            Self::Peasant => "Cpeas.def",
            Self::Halfling => "CHalf.def",
            Self::Boar => "Cboar.def",
            Self::Rogue => "Crogue.def",
            Self::Mummy => "Cmummy.def",
            Self::Nomad => "Cnomad.def",
            Self::Sharpshooter => "Csharp.def",
            Self::Troll => "Ctroll.def",
            Self::GoldGolem => "CGGOLE.def",
            Self::DiamondGolem => "CDGOLE.def",
            Self::Enchanter => "Cench.def",
            Self::FaerieDragon => "Cfdrgn.def",
            Self::RustDragon => "CRsDgn.def",
            Self::CrystalDragon => "Ccdrgn.def",
            Self::AzureDragon => "CaDrgn.def",
            // War Machines
            Self::Ballista => "smbal.def",
            Self::FirstAidTent => "SMtent.def",
            Self::Catapult => "SMCata.def",
            Self::AmmoCart => "SMCart.def",
        }
    }

    pub const fn walk_animation_time(self) -> f32 {
        match self {
            C::Pikeman => 1.15,
            C::Halberdier => 0.90,
            C::Archer => 1.00,
            C::Marksman => 1.00,
            C::Griffin => 1.00,
            C::RoyalGriffin => 1.05,
            C::Swordsman => 0.87,
            C::Crusader => 0.95,
            C::Monk => 1.00,
            C::Zealot => 1.00,
            C::Cavalier => 1.00,
            C::Champion => 0.90,
            C::Angel => 0.82,
            C::Archangel => 0.82,

            C::Centaur => 0.50,
            C::CentaurCaptain => 0.50,
            C::Dwarf => 0.98,
            C::BattleDwarf => 0.97,
            C::WoodElf => 1.02,
            C::GrandElf => 1.02,
            C::Pegasus => 0.72,
            C::SilverPegasus => 0.72,
            C::DendroidGuard => 1.55,
            C::DendroidSoldier => 1.55,
            C::Unicorn => 1.20,
            C::WarUnicorn => 1.20,
            C::GreenDragon => 0.60,
            C::GoldDragon => 0.60,

            C::Gremlin => 1.00,
            C::MasterGremlin => 0.75,
            C::StoneGargoyle => 0.70,
            C::ObsidianGargoyle => 0.70,
            C::IronGolem => 1.20,
            C::StoneGolem => 1.45,
            C::Mage => 1.00,
            C::ArchMage => 1.00,
            C::Genie => 1.00,
            C::MasterGenie => 1.00,
            C::Naga => 1.00,
            C::NagaQueen => 1.00,
            C::Giant => 1.38,
            C::Titan => 1.38,

            C::Imp => 1.25,
            C::Familiar => 1.30,
            C::Gog => 1.27,
            C::Magog => 1.33,
            C::HellHound => 1.00,
            C::Cerberus => 1.00,
            C::Demon => 0.93,
            C::HornedDemon => 0.93,
            C::PitFiend => 1.00,
            C::PitLord => 1.00,
            C::Efreeti => 1.00,
            C::EfreetSultan => 1.00,
            C::Devil => 1.00,
            C::ArchDevil => 1.00,

            C::Skeleton => 1.00,
            C::SkeletonWarrior => 1.00,
            C::WalkingDead => 1.30,
            C::Zombie => 1.30,
            C::Wight => 1.00,
            C::Wraith => 1.00,
            C::Vampire => 1.00,
            C::VampireLord => 1.00,
            C::Lich => 1.00,
            C::PowerLich => 1.00,
            C::BlackKnight => 1.00,
            C::DreadKnight => 1.00,
            C::BoneDragon => 0.75,
            C::GhostDragon => 0.75,

            C::Troglodyte => 0.80,
            C::InfernalTroglodyte => 0.80,
            C::Harpy => 0.85,
            C::HarpyHag => 0.85,
            C::Beholder => 1.00,
            C::EvilEye => 1.00,
            C::Medusa => 1.00,
            C::MedusaQueen => 1.00,
            C::Minotaur => 1.05,
            C::MinotaurKing => 1.05,
            C::Manticore => 0.80,
            C::Scorpicore => 0.80,
            C::RedDragon => 0.60,
            C::BlackDragon => 0.60,

            C::Goblin => 1.21,
            C::Hobgoblin => 1.24,
            C::WolfRider => 0.93,
            C::WolfRaider => 0.93,
            C::Orc => 1.00,
            C::OrcChieftain => 1.00,
            C::Ogre => 1.28,
            C::OgreMagi => 1.28,
            C::Roc => 1.00,
            C::Thunderbird => 1.00,
            C::Cyclops => 1.00,
            C::CyclopsKing => 1.00,
            C::Behemoth => 1.17,
            C::AncientBehemoth => 1.17,

            C::Gnoll => 1.00,
            C::GnollMarauder => 1.00,
            C::Lizardman => 0.90,
            C::LizardWarrior => 0.90,
            C::Gorgon => 1.00,
            C::MightyGorgon => 1.00,
            C::SerpentFly => 0.77,
            C::DragonFly => 0.77,
            C::Basilisk => 1.00,
            C::GreaterBasilisk => 1.00,
            C::Wyvern => 0.67,
            C::WyvernMonarch => 0.67,
            C::Hydra => 1.00,
            C::ChaosHydra => 1.00,

            C::AirElemental => 0.50,
            C::EarthElemental => 1.00,
            C::FireElemental => 0.50,
            C::WaterElemental => 0.87,
            C::GoldGolem => 1.20,
            C::DiamondGolem => 1.27,
            C::Pixie => 1.00,
            C::Sprite => 1.00,
            C::PsychicElemental => 1.00,
            C::MagicElemental => 1.00,
            C::IceElemental => 1.00,
            C::MagmaElemental => 0.77,
            C::StormElemental => 1.33,
            C::EnergyElemental => 0.67,
            C::Firebird => 1.00,
            C::Phoenix => 1.00,

            C::AzureDragon => 0.60,
            C::CrystalDragon => 0.60,
            C::FaerieDragon => 0.60,
            C::RustDragon => 0.60,
            C::Enchanter => 1.00,
            C::Sharpshooter => 1.02,
            C::Halfling => 1.00,
            C::Peasant => 1.00,
            C::Boar => 1.00,
            C::Mummy => 1.00,
            C::Nomad => 1.00,
            C::Rogue => 1.00,
            C::Troll => 1.00,

            C::Catapult | C::Ballista | C::FirstAidTent | C::AmmoCart => unreachable!(),
        }
    }
}
