use serde::Deserialize;

pub mod abilities;
pub mod classes;

use classes::Class;

#[derive(Clone, Copy, Deserialize)]
pub enum Hero {
    Christian,
    Edric,
    Orrin,
    Sorsha,
    Sylvia,
    Tyris,
    Valeska,
    Catherine,
    HaartFresh,
    Roland,
    SirMullich,
    Adela,
    Adelaide,
    Caitlin,
    Cuthbert,
    Ingham,
    Loynis,
    Rion,
    Sanya,
    Clancy,
    Ivor,
    Jenova,
    Kyrre,
    Mephala,
    Ryland,
    Thorgrim,
    Ufretin,
    Gelu,
    Aeris,
    Alagar,
    Coronius,
    Elleshar,
    Gem,
    Malcom,
    Melodia,
    Uland,
    Fafner,
    Iona,
    Josephine,
    Neela,
    Piquedram,
    Rissa,
    Thane,
    Torosar,
    Aine,
    Astral,
    Cyra,
    Daremyth,
    Halon,
    Serena,
    Solmyr,
    Theodorus,
    Dracon,
    Calh,
    Fiona,
    Ignatius,
    Marius,
    Nymus,
    Octavia,
    Pyre,
    Rashka,
    Xeron,
    Ash,
    Axsis,
    Ayden,
    Calid,
    Olema,
    Xarfax,
    Xyron,
    Zydar,
    Charna,
    Clavius,
    Galthran,
    Isra,
    Moandor,
    Straker,
    Tamika,
    Vokial,
    HaartStale,
    Aislinn,
    Nagash,
    Nimbus,
    Sandro,
    Septienna,
    Thant,
    Vidomina,
    Xsi,
    Ajit,
    Arlach,
    Dace,
    Damacon,
    Gunnar,
    Lorelei,
    Shakti,
    Synca,
    Mutare,
    MutareDrake,
    Alamar,
    Darkstorn,
    Deemer,
    Geon,
    Jaegar,
    Jeddite,
    Malekith,
    Sephinroth,
    CragHack,
    Gretchin,
    Gurnisson,
    Jabarkas,
    Krellion,
    Shiva,
    Tyraxor,
    Yog,
    Boragus,
    Kilgor,
    Dessa,
    Gird,
    Gundula,
    Oris,
    Saurug,
    Terek,
    Vey,
    Zubin,
    Alkin,
    Broghild,
    Bron,
    Drakon,
    Gerwulf,
    Korbac,
    Tazar,
    Wystan,
    Andra,
    Merist,
    Mirlanda,
    Rosic,
    Styg,
    Tiva,
    Verdish,
    Voy,
    Adrienne,
    Erdamon,
    Fiur,
    Ignissa,
    Kalt,
    Lacus,
    Monere,
    Pasis,
    Thunar,
    Aenain,
    Brissa,
    Ciele,
    Gelare,
    Grindan,
    Inteus,
    Labetha,
    Luna,
}

pub struct Stats {
    pub attack: i32,
    pub defence: i32,
    pub power: i32,
    pub knowledge: i32,
}

impl Hero {
    pub const fn class(self) -> Class {
        match self {
            Hero::Christian => Class::Knight,
            Hero::Edric => Class::Knight,
            Hero::Orrin => Class::Knight,
            Hero::Sorsha => Class::Knight,
            Hero::Sylvia => Class::Knight,
            Hero::Tyris => Class::Knight,
            Hero::Valeska => Class::Knight,
            Hero::Catherine => Class::Knight,
            Hero::HaartFresh => Class::Knight,
            Hero::Roland => Class::Knight,
            Hero::SirMullich => Class::Knight,
            Hero::Adela => Class::Cleric,
            Hero::Adelaide => Class::Cleric,
            Hero::Caitlin => Class::Cleric,
            Hero::Cuthbert => Class::Cleric,
            Hero::Ingham => Class::Cleric,
            Hero::Loynis => Class::Cleric,
            Hero::Rion => Class::Cleric,
            Hero::Sanya => Class::Cleric,

            Hero::Clancy => Class::Ranger,
            Hero::Ivor => Class::Ranger,
            Hero::Jenova => Class::Ranger,
            Hero::Kyrre => Class::Ranger,
            Hero::Mephala => Class::Ranger,
            Hero::Ryland => Class::Ranger,
            Hero::Thorgrim => Class::Ranger,
            Hero::Ufretin => Class::Ranger,
            Hero::Gelu => Class::Ranger,
            Hero::Aeris => Class::Druid,
            Hero::Alagar => Class::Druid,
            Hero::Coronius => Class::Druid,
            Hero::Elleshar => Class::Druid,
            Hero::Gem => Class::Druid,
            Hero::Malcom => Class::Druid,
            Hero::Melodia => Class::Druid,
            Hero::Uland => Class::Druid,

            Hero::Fafner => Class::Alchemist,
            Hero::Iona => Class::Alchemist,
            Hero::Josephine => Class::Alchemist,
            Hero::Neela => Class::Alchemist,
            Hero::Piquedram => Class::Alchemist,
            Hero::Rissa => Class::Alchemist,
            Hero::Thane => Class::Alchemist,
            Hero::Torosar => Class::Alchemist,
            Hero::Aine => Class::Wizard,
            Hero::Astral => Class::Wizard,
            Hero::Cyra => Class::Wizard,
            Hero::Daremyth => Class::Wizard,
            Hero::Halon => Class::Wizard,
            Hero::Serena => Class::Wizard,
            Hero::Solmyr => Class::Wizard,
            Hero::Theodorus => Class::Wizard,
            Hero::Dracon => Class::Wizard,

            Hero::Calh => Class::Demoniac,
            Hero::Fiona => Class::Demoniac,
            Hero::Ignatius => Class::Demoniac,
            Hero::Marius => Class::Demoniac,
            Hero::Nymus => Class::Demoniac,
            Hero::Octavia => Class::Demoniac,
            Hero::Pyre => Class::Demoniac,
            Hero::Rashka => Class::Demoniac,
            Hero::Xeron => Class::Demoniac,
            Hero::Ash => Class::Heretic,
            Hero::Axsis => Class::Heretic,
            Hero::Ayden => Class::Heretic,
            Hero::Calid => Class::Heretic,
            Hero::Olema => Class::Heretic,
            Hero::Xarfax => Class::Heretic,
            Hero::Xyron => Class::Heretic,
            Hero::Zydar => Class::Heretic,

            Hero::Charna => Class::DeathKnight,
            Hero::Clavius => Class::DeathKnight,
            Hero::Galthran => Class::DeathKnight,
            Hero::Isra => Class::DeathKnight,
            Hero::Moandor => Class::DeathKnight,
            Hero::Straker => Class::DeathKnight,
            Hero::Tamika => Class::DeathKnight,
            Hero::Vokial => Class::DeathKnight,
            Hero::HaartStale => Class::DeathKnight,
            Hero::Aislinn => Class::Necromancer,
            Hero::Nagash => Class::Necromancer,
            Hero::Nimbus => Class::Necromancer,
            Hero::Sandro => Class::Necromancer,
            Hero::Septienna => Class::Necromancer,
            Hero::Thant => Class::Necromancer,
            Hero::Vidomina => Class::Necromancer,
            Hero::Xsi => Class::Necromancer,

            Hero::Ajit => Class::Overlord,
            Hero::Arlach => Class::Overlord,
            Hero::Dace => Class::Overlord,
            Hero::Damacon => Class::Overlord,
            Hero::Gunnar => Class::Overlord,
            Hero::Lorelei => Class::Overlord,
            Hero::Shakti => Class::Overlord,
            Hero::Synca => Class::Overlord,
            Hero::Mutare => Class::Overlord,
            Hero::MutareDrake => Class::Overlord,
            Hero::Alamar => Class::Warlock,
            Hero::Darkstorn => Class::Warlock,
            Hero::Deemer => Class::Warlock,
            Hero::Geon => Class::Warlock,
            Hero::Jaegar => Class::Warlock,
            Hero::Jeddite => Class::Warlock,
            Hero::Malekith => Class::Warlock,
            Hero::Sephinroth => Class::Warlock,

            Hero::CragHack => Class::Barbarian,
            Hero::Gretchin => Class::Barbarian,
            Hero::Gurnisson => Class::Barbarian,
            Hero::Jabarkas => Class::Barbarian,
            Hero::Krellion => Class::Barbarian,
            Hero::Shiva => Class::Barbarian,
            Hero::Tyraxor => Class::Barbarian,
            Hero::Yog => Class::Barbarian,
            Hero::Boragus => Class::Barbarian,
            Hero::Kilgor => Class::Barbarian,
            Hero::Dessa => Class::BattleMage,
            Hero::Gird => Class::BattleMage,
            Hero::Gundula => Class::BattleMage,
            Hero::Oris => Class::BattleMage,
            Hero::Saurug => Class::BattleMage,
            Hero::Terek => Class::BattleMage,
            Hero::Vey => Class::BattleMage,
            Hero::Zubin => Class::BattleMage,

            Hero::Alkin => Class::Beastmaster,
            Hero::Broghild => Class::Beastmaster,
            Hero::Bron => Class::Beastmaster,
            Hero::Drakon => Class::Beastmaster,
            Hero::Gerwulf => Class::Beastmaster,
            Hero::Korbac => Class::Beastmaster,
            Hero::Tazar => Class::Beastmaster,
            Hero::Wystan => Class::Beastmaster,
            Hero::Andra => Class::Witch,
            Hero::Merist => Class::Witch,
            Hero::Mirlanda => Class::Witch,
            Hero::Rosic => Class::Witch,
            Hero::Styg => Class::Witch,
            Hero::Tiva => Class::Witch,
            Hero::Verdish => Class::Witch,
            Hero::Voy => Class::Witch,
            Hero::Adrienne => Class::Witch,

            Hero::Erdamon => Class::Planeswalker,
            Hero::Fiur => Class::Planeswalker,
            Hero::Ignissa => Class::Planeswalker,
            Hero::Kalt => Class::Planeswalker,
            Hero::Lacus => Class::Planeswalker,
            Hero::Monere => Class::Planeswalker,
            Hero::Pasis => Class::Planeswalker,
            Hero::Thunar => Class::Planeswalker,
            Hero::Aenain => Class::Elementalist,
            Hero::Brissa => Class::Elementalist,
            Hero::Ciele => Class::Elementalist,
            Hero::Gelare => Class::Elementalist,
            Hero::Grindan => Class::Elementalist,
            Hero::Inteus => Class::Elementalist,
            Hero::Labetha => Class::Elementalist,
            Hero::Luna => Class::Elementalist,
        }
    }
}
