use super::Creature;

pub struct CreatureStats {
    pub level: u8,
    pub attack: u8,
    pub defence: u8,
    pub damage: (u8, u8),
    pub health: u16,
    pub speed: u8,
    pub ammo_capacity: u8,
}

type CS = CreatureStats;

impl Creature {
    pub const fn base_stats(&self) -> CreatureStats {
        match self {
            // Castle
            Self::Pikeman => CS {
                level: 1,
                attack: 4,
                defence: 5,
                damage: (1, 3),
                health: 10,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Halberdier => CS {
                level: 1,
                attack: 6,
                defence: 5,
                damage: (2, 3),
                health: 10,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Archer => CS {
                level: 2,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::Marksman => CS {
                level: 2,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::Griffin => CS {
                level: 3,
                attack: 8,
                defence: 8,
                damage: (3, 6),
                health: 25,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::RoyalGriffin => CS {
                level: 3,
                attack: 9,
                defence: 9,
                damage: (3, 6),
                health: 25,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Swordsman => CS {
                level: 4,
                attack: 10,
                defence: 12,
                damage: (6, 9),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Crusader => CS {
                level: 4,
                attack: 12,
                defence: 12,
                damage: (7, 10),
                health: 35,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Monk => CS {
                level: 5,
                attack: 12,
                defence: 7,
                damage: (10, 12),
                health: 30,
                speed: 5,
                ammo_capacity: 12,
            },
            Self::Zealot => CS {
                level: 5,
                attack: 12,
                defence: 10,
                damage: (10, 12),
                health: 30,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Cavalier => CS {
                level: 6,
                attack: 15,
                defence: 15,
                damage: (15, 25),
                health: 100,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Champion => CS {
                level: 6,
                attack: 16,
                defence: 16,
                damage: (20, 25),
                health: 100,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Angel => CS {
                level: 7,
                attack: 20,
                defence: 20,
                damage: (50, 50),
                health: 200,
                speed: 12,
                ammo_capacity: 0,
            },
            Self::Archangel => CS {
                level: 7,
                attack: 30,
                defence: 30,
                damage: (50, 50),
                health: 250,
                speed: 18,
                ammo_capacity: 0,
            },
            // Rampart
            Self::Centaur => CS {
                level: 1,
                attack: 5,
                defence: 3,
                damage: (2, 3),
                health: 8,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::CentaurCaptain => CS {
                level: 1,
                attack: 6,
                defence: 3,
                damage: (2, 3),
                health: 10,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Dwarf => CS {
                level: 2,
                attack: 6,
                defence: 7,
                damage: (2, 4),
                health: 20,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::BattleDwarf => CS {
                level: 2,
                attack: 7,
                defence: 7,
                damage: (2, 4),
                health: 20,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::WoodElf => CS {
                level: 3,
                attack: 9,
                defence: 5,
                damage: (3, 5),
                health: 15,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::GrandElf => CS {
                level: 3,
                attack: 9,
                defence: 5,
                damage: (3, 5),
                health: 15,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Pegasus => CS {
                level: 4,
                attack: 9,
                defence: 8,
                damage: (5, 9),
                health: 30,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::SilverPegasus => CS {
                level: 4,
                attack: 9,
                defence: 10,
                damage: (5, 9),
                health: 30,
                speed: 12,
                ammo_capacity: 0,
            },
            Self::DendroidGuard => CS {
                level: 5,
                attack: 9,
                defence: 12,
                damage: (10, 14),
                health: 55,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::DendroidSoldier => CS {
                level: 5,
                attack: 9,
                defence: 12,
                damage: (10, 14),
                health: 65,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Unicorn => CS {
                level: 6,
                attack: 15,
                defence: 14,
                damage: (18, 22),
                health: 90,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WarUnicorn => CS {
                level: 6,
                attack: 15,
                defence: 14,
                damage: (18, 22),
                health: 110,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::GreenDragon => CS {
                level: 7,
                attack: 18,
                defence: 18,
                damage: (40, 50),
                health: 180,
                speed: 10,
                ammo_capacity: 0,
            },
            Self::GoldDragon => CS {
                level: 7,
                attack: 27,
                defence: 27,
                damage: (40, 50),
                health: 250,
                speed: 16,
                ammo_capacity: 0,
            },
            // Tower
            Self::Gremlin => CS {
                level: 1,
                attack: 3,
                defence: 3,
                damage: (1, 2),
                health: 4,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::MasterGremlin => CS {
                level: 1,
                attack: 4,
                defence: 4,
                damage: (1, 2),
                health: 4,
                speed: 5,
                ammo_capacity: 8,
            },
            Self::StoneGargoyle => CS {
                level: 2,
                attack: 6,
                defence: 6,
                damage: (2, 3),
                health: 16,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::ObsidianGargoyle => CS {
                level: 2,
                attack: 7,
                defence: 7,
                damage: (2, 3),
                health: 16,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::StoneGolem => CS {
                level: 3,
                attack: 7,
                defence: 10,
                damage: (4, 5),
                health: 30,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::IronGolem => CS {
                level: 3,
                attack: 9,
                defence: 10,
                damage: (4, 5),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Mage => CS {
                level: 4,
                attack: 11,
                defence: 8,
                damage: (7, 9),
                health: 25,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::ArchMage => CS {
                level: 4,
                attack: 12,
                defence: 9,
                damage: (7, 9),
                health: 30,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Genie => CS {
                level: 5,
                attack: 12,
                defence: 12,
                damage: (13, 16),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::MasterGenie => CS {
                level: 5,
                attack: 12,
                defence: 12,
                damage: (13, 16),
                health: 40,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Naga => CS {
                level: 6,
                attack: 16,
                defence: 13,
                damage: (20, 20),
                health: 110,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::NagaQueen => CS {
                level: 6,
                attack: 16,
                defence: 13,
                damage: (30, 30),
                health: 110,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Giant => CS {
                level: 7,
                attack: 19,
                defence: 16,
                damage: (40, 60),
                health: 150,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Titan => CS {
                level: 7,
                attack: 24,
                defence: 24,
                damage: (40, 60),
                health: 300,
                speed: 11,
                ammo_capacity: 24,
            },
            // Inferno
            Self::Imp => CS {
                level: 1,
                attack: 2,
                defence: 3,
                damage: (1, 2),
                health: 4,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Familiar => CS {
                level: 1,
                attack: 4,
                defence: 4,
                damage: (1, 2),
                health: 4,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Gog => CS {
                level: 2,
                attack: 6,
                defence: 4,
                damage: (2, 4),
                health: 13,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::Magog => CS {
                level: 2,
                attack: 7,
                defence: 4,
                damage: (2, 4),
                health: 13,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::HellHound => CS {
                level: 3,
                attack: 10,
                defence: 6,
                damage: (2, 7),
                health: 25,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Cerberus => CS {
                level: 3,
                attack: 10,
                defence: 8,
                damage: (2, 7),
                health: 25,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Demon => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (7, 9),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::HornedDemon => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (7, 9),
                health: 40,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PitFiend => CS {
                level: 5,
                attack: 13,
                defence: 13,
                damage: (13, 17),
                health: 45,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PitLord => CS {
                level: 5,
                attack: 13,
                defence: 13,
                damage: (13, 17),
                health: 45,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Efreeti => CS {
                level: 6,
                attack: 16,
                defence: 12,
                damage: (16, 24),
                health: 90,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::EfreetSultan => CS {
                level: 6,
                attack: 16,
                defence: 14,
                damage: (16, 24),
                health: 90,
                speed: 13,
                ammo_capacity: 0,
            },
            Self::Devil => CS {
                level: 7,
                attack: 19,
                defence: 21,
                damage: (30, 40),
                health: 160,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::ArchDevil => CS {
                level: 7,
                attack: 26,
                defence: 28,
                damage: (30, 40),
                health: 200,
                speed: 17,
                ammo_capacity: 0,
            },
            // Necropolis
            Self::Skeleton => CS {
                level: 1,
                attack: 5,
                defence: 4,
                damage: (1, 3),
                health: 6,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::SkeletonWarrior => CS {
                level: 1,
                attack: 6,
                defence: 6,
                damage: (1, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::WalkingDead => CS {
                level: 2,
                attack: 5,
                defence: 5,
                damage: (2, 3),
                health: 15,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::Zombie => CS {
                level: 2,
                attack: 5,
                defence: 5,
                damage: (2, 3),
                health: 20,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::Wight => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 18,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Wraith => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 18,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Vampire => CS {
                level: 4,
                attack: 10,
                defence: 9,
                damage: (5, 8),
                health: 30,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::VampireLord => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (5, 8),
                health: 40,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Lich => CS {
                level: 5,
                attack: 13,
                defence: 10,
                damage: (11, 13),
                health: 30,
                speed: 6,
                ammo_capacity: 12,
            },
            Self::PowerLich => CS {
                level: 5,
                attack: 13,
                defence: 10,
                damage: (11, 15),
                health: 40,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::BlackKnight => CS {
                level: 6,
                attack: 16,
                defence: 16,
                damage: (15, 30),
                health: 120,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::DreadKnight => CS {
                level: 6,
                attack: 18,
                defence: 18,
                damage: (15, 30),
                health: 120,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::BoneDragon => CS {
                level: 7,
                attack: 17,
                defence: 15,
                damage: (25, 50),
                health: 150,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::GhostDragon => CS {
                level: 7,
                attack: 19,
                defence: 17,
                damage: (25, 50),
                health: 200,
                speed: 14,
                ammo_capacity: 0,
            },
            // Dungeon
            Self::Troglodyte => CS {
                level: 1,
                attack: 4,
                defence: 3,
                damage: (1, 3),
                health: 5,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::InfernalTroglodyte => CS {
                level: 1,
                attack: 5,
                defence: 4,
                damage: (1, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Harpy => CS {
                level: 2,
                attack: 6,
                defence: 5,
                damage: (1, 4),
                health: 14,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::HarpyHag => CS {
                level: 2,
                attack: 6,
                defence: 6,
                damage: (1, 4),
                health: 14,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Beholder => CS {
                level: 3,
                attack: 9,
                defence: 7,
                damage: (3, 5),
                health: 22,
                speed: 5,
                ammo_capacity: 12,
            },
            Self::EvilEye => CS {
                level: 3,
                attack: 10,
                defence: 8,
                damage: (3, 5),
                health: 22,
                speed: 7,
                ammo_capacity: 24,
            },
            Self::Medusa => CS {
                level: 4,
                attack: 9,
                defence: 9,
                damage: (6, 8),
                health: 25,
                speed: 5,
                ammo_capacity: 4,
            },
            Self::MedusaQueen => CS {
                level: 4,
                attack: 10,
                defence: 10,
                damage: (6, 8),
                health: 30,
                speed: 6,
                ammo_capacity: 8,
            },
            Self::Minotaur => CS {
                level: 5,
                attack: 14,
                defence: 12,
                damage: (12, 20),
                health: 50,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::MinotaurKing => CS {
                level: 5,
                attack: 15,
                defence: 15,
                damage: (12, 20),
                health: 50,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Manticore => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (14, 20),
                health: 80,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Scorpicore => CS {
                level: 6,
                attack: 16,
                defence: 14,
                damage: (14, 20),
                health: 80,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::RedDragon => CS {
                level: 7,
                attack: 19,
                defence: 19,
                damage: (40, 50),
                health: 180,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::BlackDragon => CS {
                level: 7,
                attack: 25,
                defence: 25,
                damage: (40, 50),
                health: 300,
                speed: 15,
                ammo_capacity: 0,
            },
            // Stronghold
            Self::Goblin => CS {
                level: 1,
                attack: 4,
                defence: 2,
                damage: (1, 2),
                health: 5,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Hobgoblin => CS {
                level: 1,
                attack: 5,
                defence: 3,
                damage: (1, 2),
                health: 5,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WolfRider => CS {
                level: 2,
                attack: 7,
                defence: 5,
                damage: (2, 4),
                health: 10,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::WolfRaider => CS {
                level: 2,
                attack: 8,
                defence: 5,
                damage: (3, 4),
                health: 10,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::Orc => CS {
                level: 3,
                attack: 8,
                defence: 4,
                damage: (2, 5),
                health: 15,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::OrcChieftain => CS {
                level: 3,
                attack: 8,
                defence: 4,
                damage: (2, 5),
                health: 20,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::Ogre => CS {
                level: 4,
                attack: 13,
                defence: 7,
                damage: (6, 12),
                health: 40,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::OgreMagi => CS {
                level: 4,
                attack: 13,
                defence: 7,
                damage: (6, 12),
                health: 60,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Roc => CS {
                level: 5,
                attack: 13,
                defence: 11,
                damage: (11, 15),
                health: 60,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Thunderbird => CS {
                level: 5,
                attack: 13,
                defence: 11,
                damage: (11, 15),
                health: 60,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Cyclops => CS {
                level: 6,
                attack: 15,
                defence: 12,
                damage: (16, 20),
                health: 70,
                speed: 6,
                ammo_capacity: 16,
            },
            Self::CyclopsKing => CS {
                level: 6,
                attack: 17,
                defence: 13,
                damage: (16, 20),
                health: 70,
                speed: 8,
                ammo_capacity: 24,
            },
            Self::Behemoth => CS {
                level: 7,
                attack: 17,
                defence: 17,
                damage: (30, 50),
                health: 160,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::AncientBehemoth => CS {
                level: 7,
                attack: 19,
                defence: 19,
                damage: (30, 50),
                health: 300,
                speed: 9,
                ammo_capacity: 0,
            },
            // Fortress
            Self::Gnoll => CS {
                level: 1,
                attack: 3,
                defence: 5,
                damage: (2, 3),
                health: 6,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::GnollMarauder => CS {
                level: 1,
                attack: 4,
                defence: 6,
                damage: (2, 3),
                health: 6,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Lizardman => CS {
                level: 2,
                attack: 5,
                defence: 6,
                damage: (2, 3),
                health: 14,
                speed: 4,
                ammo_capacity: 12,
            },
            Self::LizardWarrior => CS {
                level: 2,
                attack: 6,
                defence: 8,
                damage: (2, 5),
                health: 15,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::SerpentFly => CS {
                level: 3,
                attack: 7,
                defence: 9,
                damage: (2, 5),
                health: 20,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::DragonFly => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (2, 5),
                health: 20,
                speed: 13,
                ammo_capacity: 0,
            },
            Self::Basilisk => CS {
                level: 4,
                attack: 11,
                defence: 11,
                damage: (6, 10),
                health: 35,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::GreaterBasilisk => CS {
                level: 4,
                attack: 12,
                defence: 12,
                damage: (6, 10),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Gorgon => CS {
                level: 5,
                attack: 10,
                defence: 14,
                damage: (12, 16),
                health: 70,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::MightyGorgon => CS {
                level: 5,
                attack: 11,
                defence: 16,
                damage: (12, 16),
                health: 70,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Wyvern => CS {
                level: 6,
                attack: 14,
                defence: 14,
                damage: (14, 18),
                health: 70,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::WyvernMonarch => CS {
                level: 6,
                attack: 14,
                defence: 14,
                damage: (18, 22),
                health: 70,
                speed: 11,
                ammo_capacity: 0,
            },
            Self::Hydra => CS {
                level: 7,
                attack: 16,
                defence: 18,
                damage: (25, 45),
                health: 175,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::ChaosHydra => CS {
                level: 7,
                attack: 18,
                defence: 20,
                damage: (25, 45),
                health: 250,
                speed: 7,
                ammo_capacity: 0,
            },
            // Conflux
            Self::Pixie => CS {
                level: 1,
                attack: 2,
                defence: 2,
                damage: (1, 2),
                health: 3,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Sprite => CS {
                level: 1,
                attack: 2,
                defence: 2,
                damage: (1, 3),
                health: 3,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::AirElemental => CS {
                level: 2,
                attack: 9,
                defence: 9,
                damage: (2, 8),
                health: 25,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::StormElemental => CS {
                level: 2,
                attack: 9,
                defence: 9,
                damage: (2, 8),
                health: 25,
                speed: 8,
                ammo_capacity: 24,
            },
            Self::WaterElemental => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (3, 7),
                health: 30,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::IceElemental => CS {
                level: 3,
                attack: 8,
                defence: 10,
                damage: (3, 7),
                health: 30,
                speed: 6,
                ammo_capacity: 24,
            },
            Self::FireElemental => CS {
                level: 4,
                attack: 10,
                defence: 8,
                damage: (4, 6),
                health: 35,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::EnergyElemental => CS {
                level: 4,
                attack: 12,
                defence: 8,
                damage: (4, 6),
                health: 35,
                speed: 8,
                ammo_capacity: 0,
            },
            Self::EarthElemental => CS {
                level: 5,
                attack: 10,
                defence: 10,
                damage: (4, 8),
                health: 40,
                speed: 4,
                ammo_capacity: 0,
            },
            Self::MagmaElemental => CS {
                level: 5,
                attack: 11,
                defence: 11,
                damage: (6, 10),
                health: 40,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::PsychicElemental => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (10, 20),
                health: 75,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::MagicElemental => CS {
                level: 6,
                attack: 15,
                defence: 13,
                damage: (15, 25),
                health: 80,
                speed: 9,
                ammo_capacity: 0,
            },
            Self::Firebird => CS {
                level: 7,
                attack: 18,
                defence: 18,
                damage: (30, 40),
                health: 150,
                speed: 15,
                ammo_capacity: 0,
            },
            Self::Phoenix => CS {
                level: 7,
                attack: 21,
                defence: 18,
                damage: (30, 40),
                health: 200,
                speed: 21,
                ammo_capacity: 0,
            },
            // Neutral
            Self::Peasant => CS {
                level: 1,
                attack: 1,
                defence: 1,
                damage: (1, 1),
                health: 1,
                speed: 3,
                ammo_capacity: 0,
            },
            Self::Halfling => CS {
                level: 1,
                attack: 4,
                defence: 2,
                damage: (1, 3),
                health: 4,
                speed: 5,
                ammo_capacity: 24,
            },
            Self::Boar => CS {
                level: 2,
                attack: 6,
                defence: 5,
                damage: (2, 3),
                health: 15,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Rogue => CS {
                level: 2,
                attack: 8,
                defence: 3,
                damage: (2, 4),
                health: 10,
                speed: 6,
                ammo_capacity: 0,
            },
            Self::Mummy => CS {
                level: 3,
                attack: 7,
                defence: 7,
                damage: (3, 5),
                health: 30,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Nomad => CS {
                level: 3,
                attack: 9,
                defence: 8,
                damage: (2, 6),
                health: 30,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::Sharpshooter => CS {
                level: 4,
                attack: 12,
                defence: 10,
                damage: (8, 10),
                health: 15,
                speed: 9,
                ammo_capacity: 32,
            },
            Self::Troll => CS {
                level: 5,
                attack: 14,
                defence: 7,
                damage: (10, 15),
                health: 40,
                speed: 7,
                ammo_capacity: 0,
            },
            Self::GoldGolem => CS {
                level: 5,
                attack: 11,
                defence: 12,
                damage: (8, 10),
                health: 50,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::DiamondGolem => CS {
                level: 6,
                attack: 13,
                defence: 12,
                damage: (10, 14),
                health: 60,
                speed: 5,
                ammo_capacity: 0,
            },
            Self::Enchanter => CS {
                level: 6,
                attack: 17,
                defence: 12,
                damage: (14, 14),
                health: 30,
                speed: 9,
                ammo_capacity: 32,
            },
            Self::FaerieDragon => CS {
                level: 7,
                attack: 20,
                defence: 20,
                damage: (20, 30),
                health: 500,
                speed: 15,
                ammo_capacity: 0,
            },
            Self::RustDragon => CS {
                level: 7,
                attack: 30,
                defence: 30,
                damage: (50, 50),
                health: 750,
                speed: 17,
                ammo_capacity: 0,
            },
            Self::CrystalDragon => CS {
                level: 7,
                attack: 40,
                defence: 40,
                damage: (60, 75),
                health: 800,
                speed: 16,
                ammo_capacity: 0,
            },
            Self::AzureDragon => CS {
                level: 7,
                attack: 50,
                defence: 50,
                damage: (70, 80),
                health: 1000,
                speed: 19,
                ammo_capacity: 0,
            },
            // War Machines
            Self::Ballista => CS {
                level: 1,
                attack: 10,
                defence: 10,
                damage: (2, 3),
                health: 250,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::FirstAidTent => CS {
                level: 1,
                attack: 0,
                defence: 0,
                damage: (0, 0),
                health: 75,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::Catapult => CS {
                level: 1,
                attack: 10,
                defence: 10,
                damage: (0, 0),
                health: 1000,
                speed: 0,
                ammo_capacity: 0,
            },
            Self::AmmoCart => CS {
                level: 1,
                attack: 0,
                defence: 5,
                damage: (0, 0),
                health: 100,
                speed: 0,
                ammo_capacity: 0,
            },
        }
    }

    pub fn is_ranged(&self) -> bool {
        self.base_stats().ammo_capacity != 0
    }
}