[package]
name = "gridpos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
strum = "0.19"
strum_macros = "0.19"

creature = { path = "../creature" }
