use strum::EnumCount;
use strum_macros::{EnumCount, EnumIter};

use super::Creature;

#[derive(Clone, Copy, EnumCount, EnumIter)]
pub enum CreatureSound {
    Attack,
    Defend,
    StartMoving,
    Move,
    EndMoving,
    Shoot,
    Wince,
    Killed,
}

pub struct CreatureSounds([Option<&'static str>; CreatureSound::COUNT]);

impl CreatureSounds {
    pub fn get(&self, sound: CreatureSound) -> Option<&'static str> {
        self.0[sound as usize]
    }
}

impl Creature {
    pub fn sounds(&self) -> CreatureSounds {
        match self {
            Self::Angel => CreatureSounds([
                Some("ANGLATTK"),
                Some("ANGLDFND"),
                None,
                Some("ANGLMOVE"),
                None,
                None,
                Some("ANGLWNCE"),
                Some("ANGLKILL"),
            ]),
            Self::Archangel => CreatureSounds([
                Some("AAGLATTK"),
                Some("AAGLDFND"),
                None,
                Some("AAGLMOVE"),
                None,
                None,
                Some("AAGLWNCE"),
                Some("AAGLKILL"),
            ]),
            Self::Archer => CreatureSounds([
                Some("LCRSATTK"),
                Some("LCRSDFND"),
                None,
                Some("LCRSMOVE"),
                None,
                Some("LCRSSHOT"),
                Some("LCRSWNCE"),
                Some("LCRSKILL"),
            ]),
            Self::Cavalier => CreatureSounds([
                Some("CAVAATTK"),
                Some("CAVADFND"),
                None,
                Some("CAVAMOVE"),
                None,
                None,
                Some("CAVAWNCE"),
                Some("CAVAKILL"),
            ]),
            Self::Champion => CreatureSounds([
                Some("CHMPATTK"),
                Some("CHMPDFND"),
                None,
                Some("CHMPMOVE"),
                None,
                None,
                Some("CHMPWNCE"),
                Some("CHMPKILL"),
            ]),
            Self::Crusader => CreatureSounds([
                Some("CRUSATTK"),
                Some("CRUSDFND"),
                None,
                Some("CRUSMOVE"),
                None,
                None,
                Some("CRUSWNCE"),
                Some("CRUSKILL"),
            ]),
            Self::Griffin => CreatureSounds([
                Some("GRIFATTK"),
                Some("GRIFDFND"),
                None,
                Some("GRIFMOVE"),
                None,
                None,
                Some("GRIFWNCE"),
                Some("GRIFKILL"),
            ]),
            Self::Halberdier => CreatureSounds([
                Some("HALBATTK"),
                Some("HALBDFND"),
                None,
                Some("HALBMOVE"),
                None,
                None,
                Some("HALBWNCE"),
                Some("HALBKILL"),
            ]),
            Self::Marksman => CreatureSounds([
                Some("HCRSATTK"),
                Some("HCRSDFND"),
                None,
                Some("HCRSMOVE"),
                None,
                Some("HCRSSHOT"),
                Some("HCRSWNCE"),
                Some("HCRSKILL"),
            ]),
            Self::Monk => CreatureSounds([
                Some("MONKATTK"),
                Some("MONKDFND"),
                None,
                Some("MONKMOVE"),
                None,
                Some("MONKSHOT"),
                Some("MONKWNCE"),
                Some("MONKKILL"),
            ]),
            Self::Pikeman => CreatureSounds([
                Some("PIKEATTK"),
                Some("PIKEDFND"),
                None,
                Some("PIKEMOVE"),
                None,
                None,
                Some("PIKEWNCE"),
                Some("PIKEKILL"),
            ]),
            Self::RoyalGriffin => CreatureSounds([
                Some("RGRFATTK"),
                Some("RGRFDFND"),
                None,
                Some("RGRFMOVE"),
                None,
                None,
                Some("RGRFWNCE"),
                Some("RGRFKILL"),
            ]),
            Self::Swordsman => CreatureSounds([
                Some("SWRDATTK"),
                Some("SWRDDFND"),
                None,
                Some("SWRDMOVE"),
                None,
                None,
                Some("SWRDWNCE"),
                Some("SWRDKILL"),
            ]),
            Self::Zealot => CreatureSounds([
                Some("ZELTATTK"),
                Some("ZELTDFND"),
                None,
                Some("ZELTMOVE"),
                None,
                Some("ZELTSHOT"),
                Some("ZELTWNCE"),
                Some("ZELTKILL"),
            ]),

            Self::AmmoCart => CreatureSounds([
                None,
                None,
                None,
                None,
                None,
                None,
                Some("CARTWNCE"),
                Some("CARTKILL"),
            ]),
            Self::Ballista => CreatureSounds([
                None,
                None,
                None,
                None,
                None,
                Some("BALLSHOT"),
                Some("BALLWNCE"),
                Some("BALLKILL"),
            ]),
            Self::Catapult => CreatureSounds([
                None,
                None,
                None,
                None,
                None,
                Some("CATASHOT"),
                Some("CATAWNCE"),
                Some("CATAKILL"),
            ]),
            Self::FirstAidTent => CreatureSounds([
                None,
                None,
                None,
                None,
                None,
                None,
                Some("FAIDWNCE"),
                Some("FAIDKILL"),
            ]),

            Self::ArchMage => CreatureSounds([
                Some("AMAGATTK"),
                Some("AMAGDFND"),
                None,
                Some("AMAGMOVE"),
                None,
                Some("AMAGSHOT"),
                Some("AMAGWNCE"),
                Some("AMAGKILL"),
            ]),
            Self::Genie => CreatureSounds([
                Some("GENIATTK"),
                Some("GENIDFND"),
                None,
                Some("GENIMOVE"),
                None,
                None,
                Some("GENIWNCE"),
                Some("GENIKILL"),
            ]),
            Self::Giant => CreatureSounds([
                Some("LTITATTK"),
                Some("LTITDFND"),
                None,
                Some("LTITMOVE"),
                None,
                None,
                Some("LTITWNCE"),
                Some("LTITKILL"),
            ]),
            Self::Gremlin => CreatureSounds([
                Some("AGRMATTK"),
                Some("AGRMDFND"),
                None,
                Some("AGRMMOVE"),
                None,
                Some("AGRMSHOT"),
                Some("AGRMWNCE"),
                Some("AGRMKILL"),
            ]),
            Self::IronGolem => CreatureSounds([
                Some("SGLMATTK"),
                Some("SGLMDFND"),
                None,
                Some("SGLMMOVE"),
                None,
                None,
                Some("SGLMWNCE"),
                Some("SGLMKILL"),
            ]),
            Self::Mage => CreatureSounds([
                Some("MAGEATTK"),
                Some("MAGEDFND"),
                None,
                Some("MAGEMOVE"),
                None,
                Some("MAGESHOT"),
                Some("MAGEWNCE"),
                Some("MAGEKILL"),
            ]),
            Self::MasterGenie => CreatureSounds([
                Some("CALFATTK"),
                Some("CALFDFND"),
                None,
                Some("CALFMOVE"),
                None,
                Some("CALFSHOT"),
                Some("CALFWNCE"),
                Some("CALFKILL"),
            ]),
            Self::MasterGremlin => CreatureSounds([
                Some("MGRMATTK"),
                Some("MGRMDFND"),
                None,
                Some("MGRMMOVE"),
                None,
                Some("MGRMSHOT"),
                Some("MGRMWNCE"),
                Some("MGRMKILL"),
            ]),
            Self::Naga => CreatureSounds([
                Some("NSENATTK"),
                Some("NSENDFND"),
                None,
                Some("NSENMOVE"),
                None,
                None,
                Some("NSENWNCE"),
                Some("NSENKILL"),
            ]),
            Self::NagaQueen => CreatureSounds([
                Some("NGRDATTK"),
                Some("NGRDDFND"),
                None,
                Some("NGRDMOVE"),
                None,
                None,
                Some("NGRDWNCE"),
                Some("NGRDKILL"),
            ]),
            Self::ObsidianGargoyle => CreatureSounds([
                Some("OGRGATTK"),
                Some("OGRGDFND"),
                None,
                Some("OGRGMOVE"),
                None,
                None,
                Some("OGRGWNCE"),
                Some("OGRGKILL"),
            ]),
            Self::StoneGargoyle => CreatureSounds([
                Some("SGRGATTK"),
                Some("SGRGDFND"),
                None,
                Some("SGRGMOVE"),
                None,
                None,
                Some("SGRGWNCE"),
                Some("SGRGKILL"),
            ]),
            Self::StoneGolem => CreatureSounds([
                Some("IGLMATTK"),
                Some("IGLMDFND"),
                None,
                Some("IGLMMOVE"),
                None,
                None,
                Some("IGLMWNCE"),
                Some("IGLMKILL"),
            ]),
            Self::Titan => CreatureSounds([
                Some("GTITATTK"),
                Some("GTITDFND"),
                None,
                Some("GTITMOVE"),
                None,
                Some("GTITSHOT"),
                Some("GTITWNCE"),
                Some("GTITKILL"),
            ]),

            Self::AzureDragon => CreatureSounds([
                Some("AZURATTK"),
                Some("AZURDFND"),
                None,
                Some("AZURMOVE"),
                None,
                None,
                Some("AZURWNCE"),
                Some("AZURKILL"),
            ]),
            Self::Boar => CreatureSounds([
                Some("BOARATTK"),
                Some("BOARDFND"),
                None,
                Some("BOARMOVE"),
                None,
                None,
                Some("BOARWNCE"),
                Some("BOARKILL"),
            ]),
            Self::CrystalDragon => CreatureSounds([
                Some("CRYSATTK"),
                Some("CRYSDFND"),
                None,
                Some("CRYSMOVE"),
                None,
                None,
                Some("CRYSWNCE"),
                Some("CRYSKILL"),
            ]),
            Self::DiamondGolem => CreatureSounds([
                Some("DGLMATTK"),
                Some("DGLMDFND"),
                None,
                Some("DGLMMOVE"),
                None,
                None,
                Some("DGLMWNCE"),
                Some("DGLMKILL"),
            ]),
            Self::Enchanter => CreatureSounds([
                Some("ENCHATTK"),
                Some("ENCHDFND"),
                None,
                Some("ENCHMOVE"),
                None,
                Some("ENCHSHOT"),
                Some("ENCHWNCE"),
                Some("ENCHKILL"),
            ]),
            Self::FaerieDragon => CreatureSounds([
                Some("FAERATTK"),
                Some("FAERDFND"),
                None,
                Some("FAERMOVE"),
                None,
                Some("FAERSHOT"),
                Some("FAERWNCE"),
                Some("FAERKILL"),
            ]),
            Self::GoldGolem => CreatureSounds([
                Some("GGLMATTK"),
                Some("GGLMDFND"),
                None,
                Some("GGLMMOVE"),
                None,
                None,
                Some("GGLMWNCE"),
                Some("GGLMKILL"),
            ]),
            Self::Halfling => CreatureSounds([
                Some("HALFATTK"),
                Some("HALFDFND"),
                None,
                Some("HALFMOVE"),
                None,
                Some("HALFSHOT"),
                Some("HALFWNCE"),
                Some("HALFKILL"),
            ]),
            Self::Mummy => CreatureSounds([
                Some("MUMYATTK"),
                Some("MUMYDFND"),
                None,
                Some("MUMYMOVE"),
                None,
                None,
                Some("MUMYWNCE"),
                Some("MUMYKILL"),
            ]),
            Self::Nomad => CreatureSounds([
                Some("NMADATTK"),
                Some("NMADDFND"),
                None,
                Some("NMADMOVE"),
                None,
                None,
                Some("NMADWNCE"),
                Some("NMADKILL"),
            ]),
            Self::Peasant => CreatureSounds([
                Some("PSNTATTK"),
                Some("PSNTDFND"),
                None,
                Some("PSNTMOVE"),
                None,
                None,
                Some("PSNTWNCE"),
                Some("PSNTKILL"),
            ]),
            Self::Rogue => CreatureSounds([
                Some("ROGUATTK"),
                Some("ROGUDFND"),
                None,
                Some("ROGUMOVE"),
                None,
                None,
                Some("ROGUWNCE"),
                Some("ROGUKILL"),
            ]),
            Self::RustDragon => CreatureSounds([
                Some("RUSTATTK"),
                Some("RUSTDFND"),
                None,
                Some("RUSTMOVE"),
                None,
                None,
                Some("RUSTWNCE"),
                Some("RUSTKILL"),
            ]),
            Self::Sharpshooter => CreatureSounds([
                Some("HCRSATTK"),
                Some("HCRSDFND"),
                None,
                Some("HCRSMOVE"),
                None,
                Some("HCRSSHOT"),
                Some("HCRSWNCE"),
                Some("HCRSKILL"),
            ]),
            Self::Troll => CreatureSounds([
                Some("TRLLATTK"),
                Some("TRLLDFND"),
                None,
                Some("TRLLMOVE"),
                None,
                None,
                Some("TRLLWNCE"),
                Some("TRLLKILL"),
            ]),

            Self::Basilisk => CreatureSounds([
                Some("BASLATTK"),
                Some("BASLDFND"),
                None,
                Some("BASLMOVE"),
                None,
                None,
                Some("BASLWNCE"),
                Some("BASLKILL"),
            ]),
            Self::ChaosHydra => CreatureSounds([
                Some("CHYDATTK"),
                Some("CHYDDFND"),
                None,
                Some("CHYDMOVE"),
                None,
                None,
                Some("CHYDWNCE"),
                Some("CHYDKILL"),
            ]),
            Self::DragonFly => CreatureSounds([
                Some("FDFLATTK"),
                Some("FDFLDFND"),
                None,
                Some("FDFLMOVE"),
                None,
                Some("FDFLSHOT"),
                Some("FDFLWNCE"),
                Some("FDFLKILL"),
            ]),
            Self::Gnoll => CreatureSounds([
                Some("GNOLATTK"),
                Some("GNOLDFND"),
                None,
                Some("GNOLMOVE"),
                None,
                None,
                Some("GNOLWNCE"),
                Some("GNOLKILL"),
            ]),
            Self::GnollMarauder => CreatureSounds([
                Some("GNLMATTK"),
                Some("GNLMDFND"),
                None,
                Some("GNLMMOVE"),
                None,
                None,
                Some("GNLMWNCE"),
                Some("GNLMKILL"),
            ]),
            Self::Gorgon => CreatureSounds([
                Some("CGORATTK"),
                Some("CGORDFND"),
                None,
                Some("CGORMOVE"),
                None,
                None,
                Some("CGORWNCE"),
                Some("CGORKILL"),
            ]),
            Self::GreaterBasilisk => CreatureSounds([
                Some("GBASATTK"),
                Some("GBASDFND"),
                None,
                Some("GBASMOVE"),
                None,
                None,
                Some("GBASWNCE"),
                Some("GBASKILL"),
            ]),
            Self::Hydra => CreatureSounds([
                Some("HYDRATTK"),
                Some("HYDRDFND"),
                None,
                Some("HYDRMOVE"),
                None,
                None,
                Some("HYDRWNCE"),
                Some("HYDRKILL"),
            ]),
            Self::LizardWarrior => CreatureSounds([
                Some("ALIZATTK"),
                Some("ALIZDFND"),
                None,
                Some("ALIZMOVE"),
                None,
                Some("ALIZSHOT"),
                Some("ALIZWNCE"),
                Some("ALIZKILL"),
            ]),
            Self::Lizardman => CreatureSounds([
                Some("PLIZATTK"),
                Some("PLIZDFND"),
                None,
                Some("PLIZMOVE"),
                None,
                Some("PLIZSHOT"),
                Some("PLIZWNCE"),
                Some("PLIZKILL"),
            ]),
            Self::MightyGorgon => CreatureSounds([
                Some("BGORATTK"),
                Some("BGORDFND"),
                None,
                Some("BGORMOVE"),
                None,
                None,
                Some("BGORWNCE"),
                Some("BGORKILL"),
            ]),
            Self::SerpentFly => CreatureSounds([
                Some("DFLYATTK"),
                Some("DFLYDFND"),
                None,
                Some("DFLYMOVE"),
                None,
                None,
                Some("DFLYWNCE"),
                Some("DFLYKILL"),
            ]),
            Self::Wyvern => CreatureSounds([
                Some("WYVNATTK"),
                Some("WYVNDFND"),
                None,
                Some("WYVNMOVE"),
                None,
                None,
                Some("WYVNWNCE"),
                Some("WYVNKILL"),
            ]),
            Self::WyvernMonarch => CreatureSounds([
                Some("WYVMATTK"),
                Some("WYVMDFND"),
                None,
                Some("WYVMMOVE"),
                None,
                None,
                Some("WYVMWNCE"),
                Some("WYVMKILL"),
            ]),

            Self::BlackKnight => CreatureSounds([
                Some("BKNTATTK"),
                Some("BKNTDFND"),
                None,
                Some("BKNTMOVE"),
                None,
                None,
                Some("BKNTWNCE"),
                Some("BKNTKILL"),
            ]),
            Self::BoneDragon => CreatureSounds([
                Some("BODRATTK"),
                Some("BODRDFND"),
                None,
                Some("BODRMOVE"),
                None,
                None,
                Some("BODRWNCE"),
                Some("BODRKILL"),
            ]),
            Self::DreadKnight => CreatureSounds([
                Some("BLRDATTK"),
                Some("BLRDDFND"),
                None,
                Some("BLRDMOVE"),
                None,
                None,
                Some("BLRDWNCE"),
                Some("BLRDKILL"),
            ]),
            Self::GhostDragon => CreatureSounds([
                Some("GHDRATTK"),
                Some("GHDRDFND"),
                None,
                Some("GHDRMOVE"),
                None,
                None,
                Some("GHDRWNCE"),
                Some("GHDRKILL"),
            ]),
            Self::Lich => CreatureSounds([
                Some("LICHATTK"),
                Some("LICHDFND"),
                None,
                Some("LICHMOVE"),
                None,
                Some("LICHSHOT"),
                Some("LICHWNCE"),
                Some("LICHKILL"),
            ]),
            Self::PowerLich => CreatureSounds([
                Some("PLCHATTK"),
                Some("PLCHDFND"),
                None,
                Some("PLCHMOVE"),
                None,
                Some("PLCHSHOT"),
                Some("PLCHWNCE"),
                Some("PLCHKILL"),
            ]),
            Self::Skeleton => CreatureSounds([
                Some("SKELATTK"),
                Some("SKELDFND"),
                None,
                Some("SKELMOVE"),
                None,
                None,
                Some("SKELWNCE"),
                Some("SKELKILL"),
            ]),
            Self::SkeletonWarrior => CreatureSounds([
                Some("SKLWATTK"),
                Some("SKLWDFND"),
                None,
                Some("SKLWMOVE"),
                None,
                None,
                Some("SKLWWNCE"),
                Some("SKLWKILL"),
            ]),
            Self::Vampire => CreatureSounds([
                Some("VAMPATTK"),
                Some("VAMPDFND"),
                Some("VAMPEXT1"),
                Some("VAMPMOVE"),
                Some("VAMPEXT2"),
                None,
                Some("VAMPWNCE"),
                Some("VAMPKILL"),
            ]),
            Self::VampireLord => CreatureSounds([
                Some("NOSFATTK"),
                Some("NOSFDFND"),
                Some("NOSFEXT1"),
                Some("NOSFMOVE"),
                Some("NOSFEXT2"),
                Some("NOSFSHOT"),
                Some("NOSFWNCE"),
                Some("NOSFKILL"),
            ]),
            Self::WalkingDead => CreatureSounds([
                Some("ZOMBATTK"),
                Some("ZOMBDFND"),
                None,
                Some("ZOMBMOVE"),
                None,
                None,
                Some("ZOMBWNCE"),
                Some("ZOMBKILL"),
            ]),
            Self::Zombie => CreatureSounds([
                Some("ZMBLATTK"),
                Some("ZMBLDFND"),
                None,
                Some("ZMBLMOVE"),
                None,
                None,
                Some("ZMBLWNCE"),
                Some("ZMBLKILL"),
            ]),
            Self::Wight => CreatureSounds([
                Some("WGHTATTK"),
                Some("WGHTDFND"),
                None,
                Some("WGHTMOVE"),
                None,
                None,
                Some("WGHTWNCE"),
                Some("WGHTKILL"),
            ]),
            Self::Wraith => CreatureSounds([
                Some("WRTHATTK"),
                Some("WRTHDFND"),
                None,
                Some("WRTHMOVE"),
                None,
                None,
                Some("WRTHWNCE"),
                Some("WRTHKILL"),
            ]),

            Self::AirElemental => CreatureSounds([
                Some("AELMATTK"),
                Some("AELMDFND"),
                None,
                Some("AELMMOVE"),
                None,
                None,
                Some("AELMWNCE"),
                Some("AELMKILL"),
            ]),
            Self::EarthElemental => CreatureSounds([
                Some("EELMATTK"),
                Some("EELMDFND"),
                None,
                Some("EELMMOVE"),
                None,
                None,
                Some("EELMWNCE"),
                Some("EELMKILL"),
            ]),
            Self::EnergyElemental => CreatureSounds([
                Some("ENERATTK"),
                Some("ENERDFND"),
                None,
                Some("ENERMOVE"),
                None,
                None,
                Some("ENERWNCE"),
                Some("ENERKILL"),
            ]),
            Self::FireElemental => CreatureSounds([
                Some("FELMATTK"),
                Some("FELMDFND"),
                None,
                Some("FELMMOVE"),
                None,
                None,
                Some("FELMWNCE"),
                Some("FELMKILL"),
            ]),
            Self::Firebird => CreatureSounds([
                Some("FIRBATTK"),
                Some("FIRBDFND"),
                None,
                Some("FIRBMOVE"),
                None,
                None,
                Some("FIRBWNCE"),
                Some("FIRBKILL"),
            ]),
            Self::IceElemental => CreatureSounds([
                Some("ICELATTK"),
                Some("ICELDFND"),
                None,
                Some("ICELMOVE"),
                None,
                Some("ICELSHOT"),
                Some("ICELWNCE"),
                Some("ICELKILL"),
            ]),
            Self::MagicElemental => CreatureSounds([
                Some("MGELATTK"),
                Some("MGELDFND"),
                None,
                Some("MGELMOVE"),
                None,
                None,
                Some("MGELWNCE"),
                Some("MGELKILL"),
            ]),
            Self::MagmaElemental => CreatureSounds([
                Some("MAGMATTK"),
                Some("MAGMDFND"),
                None,
                Some("MAGMMOVE"),
                None,
                None,
                Some("MAGMWNCE"),
                Some("MAGMKILL"),
            ]),
            Self::Phoenix => CreatureSounds([
                Some("PHOEATTK"),
                Some("PHOEDFND"),
                None,
                Some("PHOEMOVE"),
                None,
                None,
                Some("PHOEWNCE"),
                Some("PHOEKILL"),
            ]),
            Self::Pixie => CreatureSounds([
                Some("PIXIATTK"),
                Some("PIXIDFND"),
                None,
                Some("PIXIMOVE"),
                None,
                None,
                Some("PIXIWNCE"),
                Some("PIXIKILL"),
            ]),
            Self::PsychicElemental => CreatureSounds([
                Some("PSYCATTK"),
                Some("PSYCDFND"),
                None,
                Some("PSYCMOVE"),
                None,
                None,
                Some("PSYCWNCE"),
                Some("PSYCKILL"),
            ]),
            Self::Sprite => CreatureSounds([
                Some("SPRTATTK"),
                Some("SPRTDFND"),
                None,
                Some("SPRTMOVE"),
                None,
                None,
                Some("SPRTWNCE"),
                Some("SPRTKILL"),
            ]),
            Self::StormElemental => CreatureSounds([
                Some("STORATTK"),
                Some("STORDFND"),
                None,
                Some("STORMOVE"),
                None,
                Some("STORSHOT"),
                Some("STORWNCE"),
                Some("STORKILL"),
            ]),
            Self::WaterElemental => CreatureSounds([
                Some("WELMATTK"),
                Some("WELMDFND"),
                None,
                Some("WELMMOVE"),
                None,
                None,
                Some("WELMWNCE"),
                Some("WELMKILL"),
            ]),

            Self::ArchDevil => CreatureSounds([
                Some("ADVLATTK"),
                Some("ADVLDFND"),
                Some("ADVLEXT1"),
                Some("ADVLMOVE"),
                Some("ADVLEXT2"),
                None,
                Some("ADVLWNCE"),
                Some("ADVLKILL"),
            ]),
            Self::Cerberus => CreatureSounds([
                Some("CERBATTK"),
                Some("CERBDFND"),
                None,
                Some("CERBMOVE"),
                None,
                None,
                Some("CERBWNCE"),
                Some("CERBKILL"),
            ]),
            Self::Demon => CreatureSounds([
                Some("SHDMATTK"),
                Some("SHDMDFND"),
                None,
                Some("SHDMMOVE"),
                None,
                None,
                Some("SHDMWNCE"),
                Some("SHDMKILL"),
            ]),
            Self::Devil => CreatureSounds([
                Some("DEVLATTK"),
                Some("DEVLDFND"),
                Some("DEVLEXT1"),
                Some("DEVLMOVE"),
                Some("DEVLEXT2"),
                None,
                Some("DEVLWNCE"),
                Some("DEVLKILL"),
            ]),
            Self::Efreeti => CreatureSounds([
                Some("EFRTATTK"),
                Some("EFRTDFND"),
                None,
                Some("EFRTMOVE"),
                None,
                None,
                Some("EFRTWNCE"),
                Some("EFRTKILL"),
            ]),
            Self::EfreetSultan => CreatureSounds([
                Some("ESULATTK"),
                Some("ESULDFND"),
                None,
                Some("ESULMOVE"),
                None,
                Some("ESULSHOT"),
                Some("ESULWNCE"),
                Some("ESULKILL"),
            ]),
            Self::Familiar => CreatureSounds([
                Some("FMLRATTK"),
                Some("FMLRDFND"),
                None,
                Some("FMLRMOVE"),
                None,
                None,
                Some("FMLRWNCE"),
                Some("FMLRKILL"),
            ]),
            Self::Gog => CreatureSounds([
                Some("GOGGATTK"),
                Some("GOGGDFND"),
                None,
                Some("GOGGMOVE"),
                None,
                Some("GOGGSHOT"),
                Some("GOGGWNCE"),
                Some("GOGGKILL"),
            ]),
            Self::HellHound => CreatureSounds([
                Some("HHNDATTK"),
                Some("HHNDDFND"),
                None,
                Some("HHNDMOVE"),
                None,
                None,
                Some("HHNDWNCE"),
                Some("HHNDKILL"),
            ]),
            Self::HornedDemon => CreatureSounds([
                Some("DHDMATTK"),
                Some("DHDMDFND"),
                None,
                Some("DHDMMOVE"),
                None,
                None,
                Some("DHDMWNCE"),
                Some("DHDMKILL"),
            ]),
            Self::Imp => CreatureSounds([
                Some("IMPPATTK"),
                Some("IMPPDFND"),
                None,
                Some("IMPPMOVE"),
                None,
                None,
                Some("IMPPWNCE"),
                Some("IMPPKILL"),
            ]),
            Self::Magog => CreatureSounds([
                Some("MGOGATTK"),
                Some("MGOGDFND"),
                None,
                Some("MGOGMOVE"),
                None,
                Some("SPONTCOMB"),
                Some("MGOGWNCE"),
                Some("MGOGKILL"),
            ]),
            Self::PitFiend => CreatureSounds([
                Some("PFNDATTK"),
                Some("PFNDDFND"),
                None,
                Some("PFNDMOVE"),
                None,
                None,
                Some("PFNDWNCE"),
                Some("PFNDKILL"),
            ]),
            Self::PitLord => CreatureSounds([
                Some("PFOEATTK"),
                Some("PFOEDFND"),
                None,
                Some("PFOEMOVE"),
                None,
                None,
                Some("PFOEWNCE"),
                Some("PFOEKILL"),
            ]),

            Self::BattleDwarf => CreatureSounds([
                Some("BDRFATTK"),
                Some("BDRFDFND"),
                None,
                Some("BDRFMOVE"),
                None,
                None,
                Some("BDRFWNCE"),
                Some("BDRFKILL"),
            ]),
            Self::Centaur => CreatureSounds([
                Some("CNTRATTK"),
                Some("CNTRDFND"),
                None,
                Some("CNTRMOVE"),
                None,
                Some("CNTRSHOT"),
                Some("CNTRWNCE"),
                Some("CNTRKILL"),
            ]),
            Self::CentaurCaptain => CreatureSounds([
                Some("ECNTATTK"),
                Some("ECNTDFND"),
                None,
                Some("ECNTMOVE"),
                None,
                None,
                Some("ECNTWNCE"),
                Some("ECNTKILL"),
            ]),
            Self::DendroidGuard => CreatureSounds([
                Some("TREEATTK"),
                Some("TREEDFND"),
                None,
                Some("TREEMOVE"),
                None,
                None,
                Some("TREEWNCE"),
                Some("TREEKILL"),
            ]),
            Self::DendroidSoldier => CreatureSounds([
                Some("BTREATTK"),
                Some("BTREDFND"),
                None,
                Some("BTREMOVE"),
                None,
                None,
                Some("BTREWNCE"),
                Some("BTREKILL"),
            ]),
            Self::Dwarf => CreatureSounds([
                Some("DWRFATTK"),
                Some("DWRFDFND"),
                None,
                Some("DWRFMOVE"),
                None,
                None,
                Some("DWRFWNCE"),
                Some("DWRFKILL"),
            ]),
            Self::GoldDragon => CreatureSounds([
                Some("GODRATTK"),
                Some("GODRDFND"),
                None,
                Some("GODRMOVE"),
                None,
                None,
                Some("GODRWNCE"),
                Some("GODRKILL"),
            ]),
            Self::GrandElf => CreatureSounds([
                Some("GELFATTK"),
                Some("GELFDFND"),
                None,
                Some("GELFMOVE"),
                None,
                Some("GELFSHOT"),
                Some("GELFWNCE"),
                Some("GELFKILL"),
            ]),
            Self::GreenDragon => CreatureSounds([
                Some("GRDRATTK"),
                Some("GRDRDFND"),
                None,
                Some("GRDRMOVE"),
                None,
                None,
                Some("GRDRWNCE"),
                Some("GRDRKILL"),
            ]),
            Self::Pegasus => CreatureSounds([
                Some("PEGAATTK"),
                Some("PEGADFND"),
                None,
                Some("PEGAMOVE"),
                None,
                None,
                Some("PEGAWNCE"),
                Some("PEGAKILL"),
            ]),
            Self::SilverPegasus => CreatureSounds([
                Some("APEGATTK"),
                Some("APEGDFND"),
                None,
                Some("APEGMOVE"),
                None,
                None,
                Some("APEGWNCE"),
                Some("APEGKILL"),
            ]),
            Self::Unicorn => CreatureSounds([
                Some("UNICATTK"),
                Some("UNICDFND"),
                None,
                Some("UNICMOVE"),
                None,
                None,
                Some("UNICWNCE"),
                Some("UNICKILL"),
            ]),
            Self::WarUnicorn => CreatureSounds([
                Some("WUNCATTK"),
                Some("WUNCDFND"),
                None,
                Some("WUNCMOVE"),
                None,
                Some("WUNCSHOT"),
                Some("WUNCWNCE"),
                Some("WUNCKILL"),
            ]),
            Self::WoodElf => CreatureSounds([
                Some("WELFATTK"),
                Some("WELFDFND"),
                None,
                Some("WELFMOVE"),
                None,
                Some("WELFSHOT"),
                Some("WELFWNCE"),
                Some("WELFKILL"),
            ]),

            Self::Beholder => CreatureSounds([
                Some("BHDRATTK"),
                Some("BHDRDFND"),
                None,
                Some("BHDRMOVE"),
                None,
                Some("BHDRSHOT"),
                Some("BHDRWNCE"),
                Some("BHDRKILL"),
            ]),
            Self::BlackDragon => CreatureSounds([
                Some("BKDRATTK"),
                Some("BKDRDFND"),
                None,
                Some("BKDRMOVE"),
                None,
                None,
                Some("BKDRWNCE"),
                Some("BKDRKILL"),
            ]),
            Self::EvilEye => CreatureSounds([
                Some("EVLIATTK"),
                Some("EVLIDFND"),
                None,
                Some("EVLIMOVE"),
                None,
                Some("EVLISHOT"),
                Some("EVLIWNCE"),
                Some("EVLIKILL"),
            ]),
            Self::Harpy => CreatureSounds([
                Some("HARPATTK"),
                Some("HARPDFND"),
                None,
                Some("HARPMOVE"),
                None,
                None,
                Some("HARPWNCE"),
                Some("HARPKILL"),
            ]),
            Self::HarpyHag => CreatureSounds([
                Some("HHAGATTK"),
                Some("HHAGDFND"),
                None,
                Some("HHAGMOVE"),
                None,
                Some("HHAGSHOT"),
                Some("HHAGWNCE"),
                Some("HHAGKILL"),
            ]),
            Self::InfernalTroglodyte => CreatureSounds([
                Some("ITRGATTK"),
                Some("ITRGDFND"),
                None,
                Some("ITRGMOVE"),
                None,
                None,
                Some("ITRGWNCE"),
                Some("ITRGKILL"),
            ]),
            Self::Manticore => CreatureSounds([
                Some("MANTATTK"),
                Some("MANTDFND"),
                None,
                Some("MANTMOVE"),
                None,
                Some("MANTSHOT"),
                Some("MANTWNCE"),
                Some("MANTKILL"),
            ]),
            Self::Medusa => CreatureSounds([
                Some("MEDUATTK"),
                Some("MEDUDFND"),
                None,
                Some("MEDUMOVE"),
                None,
                Some("MEDUSHOT"),
                Some("MEDUWNCE"),
                Some("MEDUKILL"),
            ]),
            Self::MedusaQueen => CreatureSounds([
                Some("MEDQATTK"),
                Some("MEDQDFND"),
                None,
                Some("MEDQMOVE"),
                None,
                Some("MEDQSHOT"),
                Some("MEDQWNCE"),
                Some("MEDQKILL"),
            ]),
            Self::Minotaur => CreatureSounds([
                Some("MINOATTK"),
                Some("MINODFND"),
                None,
                Some("MINOMOVE"),
                None,
                None,
                Some("MINOWNCE"),
                Some("MINOKILL"),
            ]),
            Self::MinotaurKing => CreatureSounds([
                Some("MINKATTK"),
                Some("MINKDFND"),
                None,
                Some("MINKMOVE"),
                None,
                Some("MINKSHOT"),
                Some("MINKWNCE"),
                Some("MINKKILL"),
            ]),
            Self::RedDragon => CreatureSounds([
                Some("RDDRATTK"),
                Some("RDDRDFND"),
                None,
                Some("RDDRMOVE"),
                None,
                None,
                Some("RDDRWNCE"),
                Some("RDDRKILL"),
            ]),
            Self::Scorpicore => CreatureSounds([
                Some("SCRPATTK"),
                Some("SCRPDFND"),
                None,
                Some("SCRPMOVE"),
                None,
                Some("SCRPSHOT"),
                Some("SCRPWNCE"),
                Some("SCRPKILL"),
            ]),
            Self::Troglodyte => CreatureSounds([
                Some("TROGATTK"),
                Some("TROGDFND"),
                None,
                Some("TROGMOVE"),
                None,
                None,
                Some("TROGWNCE"),
                Some("TROGKILL"),
            ]),

            Self::AncientBehemoth => CreatureSounds([
                Some("BMTHATTK"),
                Some("BMTHDFND"),
                None,
                Some("BMTHMOVE"),
                None,
                None,
                Some("BMTHWNCE"),
                Some("BMTHKILL"),
            ]),
            Self::Behemoth => CreatureSounds([
                Some("YBMHATTK"),
                Some("YBMHDFND"),
                None,
                Some("YBMHMOVE"),
                None,
                None,
                Some("YBMHWNCE"),
                Some("YBMHKILL"),
            ]),
            Self::Cyclops => CreatureSounds([
                Some("CCYCATTK"),
                Some("CCYCDFND"),
                None,
                Some("CCYCMOVE"),
                None,
                Some("CCYCSHOT"),
                Some("CCYCWNCE"),
                Some("CCYCKILL"),
            ]),
            Self::CyclopsKing => CreatureSounds([
                Some("CYCLATTK"),
                Some("CYCLDFND"),
                None,
                Some("CYCLMOVE"),
                None,
                Some("CYCLSHOT"),
                Some("CYCLWNCE"),
                Some("CYCLKILL"),
            ]),
            Self::Goblin => CreatureSounds([
                Some("GBLNATTK"),
                Some("GBLNDFND"),
                None,
                Some("GBLNMOVE"),
                None,
                None,
                Some("GBLNWNCE"),
                Some("GBLNKILL"),
            ]),
            Self::WolfRider => CreatureSounds([
                Some("GWRDATTK"),
                Some("GWRDDFND"),
                None,
                Some("GWRDMOVE"),
                None,
                None,
                Some("GWRDWNCE"),
                Some("GWRDKILL"),
            ]),
            Self::Hobgoblin => CreatureSounds([
                Some("HGOBATTK"),
                Some("HGOBDFND"),
                None,
                Some("HGOBMOVE"),
                None,
                None,
                Some("HGOBWNCE"),
                Some("HGOBKILL"),
            ]),
            Self::WolfRaider => CreatureSounds([
                Some("HGWRATTK"),
                Some("HGWRDFND"),
                None,
                Some("HGWRMOVE"),
                None,
                None,
                Some("HGWRWNCE"),
                Some("HGWRKILL"),
            ]),
            Self::Ogre => CreatureSounds([
                Some("OGREATTK"),
                Some("OGREDFND"),
                None,
                Some("OGREMOVE"),
                None,
                None,
                Some("OGREWNCE"),
                Some("OGREKILL"),
            ]),
            Self::OgreMagi => CreatureSounds([
                Some("OGRMATTK"),
                Some("OGRMDFND"),
                None,
                Some("OGRMMOVE"),
                None,
                Some("OGRMSHOT"),
                Some("OGRMWNCE"),
                Some("OGRMKILL"),
            ]),
            Self::Orc => CreatureSounds([
                Some("OORCATTK"),
                Some("OORCDFND"),
                None,
                Some("OORCMOVE"),
                None,
                Some("OORCSHOT"),
                Some("OORCWNCE"),
                Some("OORCKILL"),
            ]),
            Self::OrcChieftain => CreatureSounds([
                Some("ORCCATTK"),
                Some("ORCCDFND"),
                None,
                Some("ORCCMOVE"),
                None,
                Some("ORCCSHOT"),
                Some("ORCCWNCE"),
                Some("ORCCKILL"),
            ]),
            Self::Roc => CreatureSounds([
                Some("ROCCATTK"),
                Some("ROCCDFND"),
                None,
                Some("ROCCMOVE"),
                None,
                None,
                Some("ROCCWNCE"),
                Some("ROCCKILL"),
            ]),
            Self::Thunderbird => CreatureSounds([
                Some("TBRDATTK"),
                Some("TBRDDFND"),
                None,
                Some("TBRDMOVE"),
                None,
                None,
                Some("TBRDWNCE"),
                Some("TBRDKILL"),
            ]),
        }
    }
}
